USE GD2C2022
GO

-----------------------------------------
---------- CREACIÓN DE ESQUEMA ----------
-----------------------------------------

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'LOS_SELECTOS')
BEGIN
    EXEC ('CREATE SCHEMA LOS_SELECTOS')
	PRINT('Esquema LOS_SELECTOS creado')
END
GO

---------------------------------------------
---------- BORRADO DE FOREIGN KEYS ----------
---------------------------------------------

IF Object_id('LOS_SELECTOS.BORRAR_FOREIGN_KEYS') IS NOT NULL
  DROP PROCEDURE BORRAR_FOREIGN_KEYS
GO 

CREATE PROCEDURE LOS_SELECTOS.BORRAR_FOREIGN_KEYS
AS
	DECLARE @query nvarchar(255)
	DECLARE query_cursor CURSOR FOR
		SELECT 'ALTER TABLE '
		+ object_schema_name(fk.parent_object_id)
		+ '.[' + Object_name(fk.parent_object_id)
		+ '] DROP CONSTRAINT ' + fk.name query
		FROM sys.foreign_keys fk
	OPEN query_cursor
	FETCH NEXT FROM query_cursor INTO @query
	WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC sp_executesql
			@query
			FETCH NEXT FROM query_cursor INTO @query
		END
	CLOSE query_cursor
	DEALLOCATE query_cursor
GO

---------------------------------------------
------------- BORRADO DE TABLAS -------------
---------------------------------------------

IF Object_id('LOS_SELECTOS.BORRAR_TABLAS') IS NOT NULL
	DROP PROCEDURE LOS_SELECTOS.BORRAR_TABLAS
GO

CREATE PROCEDURE LOS_SELECTOS.BORRAR_TABLAS
AS
	DECLARE @query nvarchar(255)
	DECLARE query_cursor CURSOR FOR
	SELECT 'DROP TABLE LOS_SELECTOS.' + name
			FROM  sys.tables
			WHERE schema_id = (SELECT schema_id FROM sys.schemas WHERE name = 'LOS_SELECTOS')
	OPEN query_cursor
    FETCH NEXT FROM query_cursor INTO @query
    WHILE @@FETCH_STATUS = 0
      BEGIN
          EXEC sp_executesql
            @query
          FETCH NEXT FROM query_cursor INTO @query
      END
    CLOSE query_cursor
    DEALLOCATE query_cursor
GO

---------------------------------------------
----------- BORRADO DE PROCEDURES -----------
---------------------------------------------

IF Object_id('LOS_SELECTOS.BORRAR_PROCEDURES') IS NOT NULL
  DROP PROCEDURE LOS_SELECTOS.BORRAR_PROCEDURES
GO

CREATE PROCEDURE LOS_SELECTOS.BORRAR_PROCEDURES
AS
    DECLARE @query nvarchar(255)
    DECLARE query_cursor CURSOR FOR
    SELECT 'DROP PROCEDURE LOS_SELECTOS.' + name
               FROM  sys.procedures
               WHERE schema_id = (SELECT schema_id FROM sys.schemas WHERE name = 'LOS_SELECTOS') AND name LIKE 'MIGRAR_%'
      OPEN query_cursor
    FETCH NEXT FROM query_cursor INTO @query
    WHILE @@FETCH_STATUS = 0
      BEGIN
          EXEC sp_executesql
            @query
          FETCH NEXT FROM query_cursor INTO @query
      END
    CLOSE query_cursor
    DEALLOCATE query_cursor
GO

------------------------------------------------------------------
---------- BORRADO DE FOREIGN KEYS, TABLAS Y PROCEDURES ----------
------------------------------------------------------------------

EXEC LOS_SELECTOS.BORRAR_FOREIGN_KEYS
EXEC LOS_SELECTOS.BORRAR_TABLAS
EXEC LOS_SELECTOS.BORRAR_PROCEDURES
GO

DROP PROCEDURE LOS_SELECTOS.BORRAR_FOREIGN_KEYS
DROP PROCEDURE LOS_SELECTOS.BORRAR_TABLAS
DROP PROCEDURE LOS_SELECTOS.BORRAR_PROCEDURES

----------------------------------------
---------- BORRADO DE ESQUEMA ----------
----------------------------------------

IF EXISTS (SELECT * FROM sys.schemas WHERE name = 'LOS_SELECTOS')
BEGIN
   DROP SCHEMA LOS_SELECTOS
   PRINT('Esquema LOS_SELECTOS borrado')
END
GO

-----------------------------------------
---------- CREACIÓN DE ESQUEMA ----------
-----------------------------------------

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'LOS_SELECTOS')
BEGIN
    EXEC ('CREATE SCHEMA LOS_SELECTOS')
	PRINT('Esquema LOS_SELECTOS creado')
END
GO

----------------------------------------
---------- CREACIÓN DE TABLAS ----------
----------------------------------------

IF OBJECT_ID('LOS_SELECTOS.PROVEEDOR', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.PROVEEDOR (
		PROVEEDOR_CUIT nvarchar(50) NOT NULL,
		PROVEEDOR_LOCALIDAD_CODIGO decimal(18,0) NOT NULL, --FK A LOCALIDAD
		PROVEEDOR_RAZON_SOCIAL nvarchar(50) NOT NULL,
		PROVEEDOR_DOMICILIO nvarchar(50) NOT NULL,
		PROVEEDOR_MAIL nvarchar(50) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.PROVEEDOR creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.LOCALIDAD', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.LOCALIDAD (
        LOCALIDAD_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        LOCALIDAD_PROVINCIA_CODIGO decimal(18,0) NOT NULL,
        LOCALIDAD_NOMBRE NVARCHAR(255) NOT NULL,
        LOCALIDAD_CODIGO_POSTAL decimal(18,0) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.LOCALIDAD creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.PROVINCIA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.PROVINCIA (
        PROVINCIA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        PROVINCIA_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.PROVINCIA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.COMPRA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.COMPRA (
        COMPRA_NUMERO decimal(19,0) NOT NULL,
        COMPRA_MEDIO_DE_PAGO_CODIGO decimal(19,0), --FK A MEDIO DE PAGO
        PROVEEDOR_CUIT nvarchar(50), --FK A PROVEEDOR
        COMPRA_FECHA date,
        COMPRA_TOTAL decimal(18,2)
	)
	PRINT('Tabla LOS_SELECTOS.COMPRA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.VENTA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.VENTA (
        VENTA_CODIGO decimal(19,0) NOT NULL,
        VENTA_CANAL_CODIGO decimal(19,0),
        VENTA_MEDIO_DE_PAGO_CODIGO decimal(19, 0),
        VENTA_CLIENTE_CODIGO decimal(19, 0), --FK A CLIENTE
        VENTA_MEDIO_ENVIO_POR_LOCALIDAD_CODIGO decimal(19, 0), --FK A MEDIO_ENVIO_POR_LOCALIDAD
        VENTA_FECHA date,
        VENTA_TOTAL decimal(18, 2)
	)
	PRINT('Tabla LOS_SELECTOS.VENTA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.MEDIO_DE_PAGO_VENTA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.MEDIO_DE_PAGO_VENTA (
        MEDIO_DE_PAGO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1) ,
        MEDIO_DE_PAGO_NOMBRE NVARCHAR(255) NOT NULL,
        MEDIO_DE_PAGO_COSTO decimal(18,2) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.MEDIO_DE_PAGO_VENTA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD (
        MEDIO_ENVIO_POR_LOCALIDAD_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        LOCALIDAD_CODIGO decimal(18,0) NOT NULL, --FK A LOCALIDAD
        MEDIO_ENVIO_CODIGO decimal(19,0) NOT NULL, --FK A MEDIO_ENVIO
        VENTA_ENVIO_PRECIO decimal(18,2) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.MEDIO_ENVIO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.MEDIO_ENVIO (
        MEDIO_ENVIO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1) ,
        MEDIO_ENVIO_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.MEDIO_ENVIO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.CLIENTE', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.CLIENTE (
		CLIENTE_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CLIENTE_NOMBRE nvarchar(255) NOT NULL,
        CLIENTE_APELLIDO nvarchar(255) NOT NULL ,
        CLIENTE_DNI decimal(18,0) NOT NULL,
        CLIENTE_DIRECCION nvarchar(255) NOT NULL,
        CLIENTE_TELEFONO decimal(18,0) NOT NULL,
        CLIENTE_MAIL nvarchar(255) NOT NULL,
        CLIENTE_FECHA_NAC date NOT NULL,
        CLIENTE_LOCALIDAD_CODIGO decimal(18,0) NOT NULL --FK A LOCALIDAD
	)
	PRINT('Tabla LOS_SELECTOS.CLIENTE creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.MATERIAL', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.MATERIAL (
		MATERIAL_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        MATERIAL_NOMBRE nvarchar(50) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.MATERIAL creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.CUPON_TIPO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.CUPON_TIPO (
        CUPON_TIPO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CUPON_TIPO_NOMBRE nvarchar(50) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.CUPON_TIPO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.CUPON', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.CUPON (
        CUPON_CODIGO nvarchar(255) NOT NULL,
        CUPON_TIPO_CODIGO decimal(19,0), --FK A CUPON_TIPO
        CUPON_FECHA_DESDE date,
        CUPON_FECHA_HASTA date,
        CUPON_VALOR decimal(18,2)
		)
	PRINT('Tabla LOS_SELECTOS.CUPON creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.CANAL', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.CANAL (
        CANAL_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        CANAL_NOMBRE nvarchar(2555),
        CANAL_COSTO decimal(18,2)
		)
	PRINT('Tabla LOS_SELECTOS.CANAL creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.VENTA_POR_CUPON', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.VENTA_POR_CUPON (
        VENTA_POR_CUPON_CODIGO decimal (19,0) NOT NULL IDENTITY(1,1),       
        CUPON_CODIGO nvarchar(255) NOT NULL, --FK A CUPON
        VENTA_CODIGO decimal(19,0) NOT NULL, --FK A VENTA
        CUPON_IMPORTE decimal(18,2) NOT NULL
		)
	PRINT('Tabla LOS_SELECTOS.VENTA_POR_CUPON creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.DESCUENTO_CONCEPTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.DESCUENTO_CONCEPTO (
        DESCUENTO_CONCEPTO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        DESCUENTO_CONCEPTO_NOMBRE nvarchar(255) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.DESCUENTO_CONCEPTO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.DESCUENTO_POR_VENTA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.DESCUENTO_POR_VENTA (
        DESCUENTO_POR_VENTA_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        DESCUENTO_CONCEPTO_CODIGO decimal(19,0) NOT NULL,
        VENTA_CODIGO decimal(19,0) NOT NULL,
        DESCUENTO_IMPORTE decimal(18,2) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.DESCUENTO_POR_VENTA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA (
        MEDIO_DE_PAGO_COMPRA_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
        MEDIO_DE_PAGO_COMPRA_NOMBRE NVARCHAR(255) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.DESCUENTO_COMPRA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.DESCUENTO_COMPRA (
        DESCUENTO_COMPRA_CODIGO decimal(19,0) NOT NULL,
        COMPRA_NUMERO decimal(19,0) NOT NULL,
        DESCUENTO_COMPRA_VALOR decimal(18,2) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.DESCUENTO_COMPRA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.COMPRA_POR_PRODUCTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.COMPRA_POR_PRODUCTO (
        COMPRA_POR_PRODUCTO_CODIGO decimal (19,0) NOT NULL IDENTITY(1,1),
        COMPRA_NUMERO decimal(19,0) NOT NULL,
        PRODUCTO_VARIANTE_CODIGO NVARCHAR(50) NOT NULL,
        PRODUCTO_CANTIDAD decimal(18,0) NOT NULL,
        PRODUCTO_PRECIO_TOTAL decimal(18,2) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.COMPRA_POR_PRODUCTO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.CATEGORIA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.CATEGORIA (
                
	CATEGORIA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        CATEGORIA_NOMBRE nvarchar(50) NOT NULL
        )
	PRINT('Tabla LOS_SELECTOS.CATEGORIA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.MARCA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.MARCA (   
		MARCA_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        MARCA_NOMBRE nvarchar(50) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.MARCA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.PRODUCTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.PRODUCTO (
		PRODUCTO_CODIGO nvarchar(50) NOT NULL,
        PRODUCTO_MARCA_CODIGO decimal(18,0) NOT NULL,
        PRODUCTO_MATERIAL_CODIGO decimal(18,0) NOT NULL,
        PRODUCTO_CATEGORIA_CODIGO decimal(18,0) NOT NULL ,
        PRODUCTO_NOMBRE nvarchar(50)  NOT NULL ,
        PRODUCTO_DESCRIPCION nvarchar(50) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.PRODUCTO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.PRODUCTO_VARIANTE', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.PRODUCTO_VARIANTE (
		PRODUCTO_VARIANTE_CODIGO nvarchar(50) NOT NULL,
        PRODUCTO_CODIGO nvarchar(50) NOT NULL,
        VARIANTE_CODIGO decimal (18,0) NOT NULL,
        PRECIO_ACTUAL_COMPRA decimal(18,2) NOT NULL,
        PRECIO_ACTUAL_VENTA decimal(18,2)
	)
	PRINT('Tabla LOS_SELECTOS.PRODUCTO_VARIANTE creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.VARIANTE', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.VARIANTE (
		VARIANTE_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1) ,
        VARIANTE_TIPO_VARIANTE_CODIGO decimal(18,0) NOT NULL,
        VARIANTE_NOMBRE nvarchar (50) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.VARIANTE creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.TIPO_VARIANTE', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.TIPO_VARIANTE (
		TIPO_VARIANTE_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
        TIPO_VARIANTE_VALOR nvarchar (50) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.TIPO_VARIANTE creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.VENTA_POR_PRODUCTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.VENTA_POR_PRODUCTO (
		VENTA_POR_PRODUCTO_CODIGO decimal(18,0) NOT NULL IDENTITY(1,1),
		PRODUCTO_VARIANTE_CODIGO nvarchar(50) NOT NULL,
		VENTA_CODIGO decimal(19,0) NOT NULL,
		PRODUCTO_CANTIDAD decimal(18,0) NOT NULL,
		PRODUCTO_PRECIO_TOTAL decimal(18,2) NOT NULL
	)
	PRINT('Tabla LOS_SELECTOS.VENTA_POR_PRODUCTO creada')
END
GO

--------------------------------------------------------
---------- CREACIÓN DE CONSTRAINTS DE TIPO PK ----------
--------------------------------------------------------

--TABLA LOCALIDAD
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_LOCALIDAD')
BEGIN
	ALTER TABLE LOS_SELECTOS.LOCALIDAD
	ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (LOCALIDAD_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.LOCALIDAD agregada')
END
GO

--TABLA PROVINCIA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROVINCIA')
BEGIN
	ALTER TABLE LOS_SELECTOS.PROVINCIA
	ADD CONSTRAINT PK_PROVINCIA PRIMARY KEY (PROVINCIA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.PROVINCIA agregada')
END
GO

--TABLA MEDIO_DE_PAGO_VENTA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_DE_PAGO_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.MEDIO_DE_PAGO_VENTA
	ADD CONSTRAINT PK_MEDIO_DE_PAGO_VENTA PRIMARY KEY (MEDIO_DE_PAGO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.MEDIO_DE_PAGO_VENTA agregada')
END
GO

--TABLA MEDIO_ENVIO_POR_LOCALIDAD
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_ENVIO_POR_LOCALIDAD')
BEGIN
	ALTER TABLE LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD
	ADD CONSTRAINT PK_MEDIO_ENVIO_POR_LOCALIDAD PRIMARY KEY (MEDIO_ENVIO_POR_LOCALIDAD_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD agregada')
END
GO

--TABLA MEDIO_ENVIO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_ENVIO')
BEGIN
	ALTER TABLE LOS_SELECTOS.MEDIO_ENVIO
	ADD CONSTRAINT PK_MEDIO_ENVIO PRIMARY KEY (MEDIO_ENVIO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.MEDIO_ENVIO agregada')
END
GO

--TABLA MEDIO_DE_PAGO_COMPRA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_DE_PAGO_COMPRA')
BEGIN
	ALTER TABLE LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA
	ADD CONSTRAINT PK_MEDIO_DE_PAGO_COMPRA PRIMARY KEY (MEDIO_DE_PAGO_COMPRA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA agregada')
END
GO

--TABLA DESCUENTO_COMPRA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DESCUENTO_COMPRA')
BEGIN
	ALTER TABLE LOS_SELECTOS.DESCUENTO_COMPRA
	ADD CONSTRAINT PK_DESCUENTO_COMPRA PRIMARY KEY (DESCUENTO_COMPRA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.DESCUENTO_COMPRA agregada')
END
GO

--TABLA COMPRA_POR_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_COMPRA_POR_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT PK_COMPRA_POR_PRODUCTO PRIMARY KEY (COMPRA_POR_PRODUCTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.COMPRA_POR_PRODUCTO agregada')
END
GO

--TABLA COMPRA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_COMPRA')
BEGIN
	ALTER TABLE LOS_SELECTOS.COMPRA
	ADD CONSTRAINT PK_COMPRA PRIMARY KEY (COMPRA_NUMERO)
	PRINT('Primary key de la tabla LOS_SELECTOS.COMPRA agregada')
END
GO

--TABLA CLIENTE
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CLIENTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.CLIENTE
	ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.CLIENTE agregada')
END
GO

--TABLA MATERIAL
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MATERIAL')
BEGIN
	ALTER TABLE LOS_SELECTOS.MATERIAL
	ADD CONSTRAINT PK_MATERIAL PRIMARY KEY (MATERIAL_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.MATERIAL agregada')
END
GO

--TABLA CUPON_TIPO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CUPON_TIPO')
BEGIN
	ALTER TABLE LOS_SELECTOS.CUPON_TIPO
	ADD CONSTRAINT PK_CUPON_TIPO PRIMARY KEY (CUPON_TIPO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.CUPON_TIPO agregada')
END
GO

--TABLA CUPON
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CUPON')
BEGIN
	ALTER TABLE LOS_SELECTOS.CUPON
	ADD CONSTRAINT PK_CUPON PRIMARY KEY (CUPON_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.CUPON agregada')
END
GO

--TABLA CANAL
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CANAL')
BEGIN
	ALTER TABLE LOS_SELECTOS.CANAL
	ADD CONSTRAINT PK_CANAL PRIMARY KEY (CANAL_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.CANAL agregada')
END
GO

--TABLA VENTA_POR_CUPON
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VENTA_POR_CUPON')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA_POR_CUPON
	ADD CONSTRAINT PK_VENTA_POR_CUPON PRIMARY KEY (VENTA_POR_CUPON_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.VENTA_POR_CUPON agregada')
END
GO

--TABLA DESCUENTO_CONCEPTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.DESCUENTO_CONCEPTO
	ADD CONSTRAINT PK_DESCUENTO_CONCEPTO PRIMARY KEY (DESCUENTO_CONCEPTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.DESCUENTO_CONCEPTO agregada')
END
GO

--TABLA DESCUENTO_POR_VENTA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DESCUENTO_POR_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.DESCUENTO_POR_VENTA
	ADD CONSTRAINT PK_DESCUENTO_POR_VENTA PRIMARY KEY (DESCUENTO_POR_VENTA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.DESCUENTO_POR_VENTA agregada')
END
GO

--TABLA PROVEEDOR
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROVEEDOR')
BEGIN
	ALTER TABLE LOS_SELECTOS.PROVEEDOR
	ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (PROVEEDOR_CUIT)
	PRINT('Primary key de la tabla LOS_SELECTOS.PROVEEDOR agregada')
END
GO

--TABLA PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.PRODUCTO
	ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (PRODUCTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.PRODUCTO agregada')
END
GO

--TABLA PRODUCTO_VARIANTE
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.PRODUCTO_VARIANTE
	ADD CONSTRAINT PK_PRODUCTO_VARIANTE PRIMARY KEY (PRODUCTO_VARIANTE_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.PRODUCTO_VARIANTE agregada')
END
GO

--TABLA VARIANTE
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VARIANTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.VARIANTE
	ADD CONSTRAINT PK_VARIANTE PRIMARY KEY (VARIANTE_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.VARIANTE agregada')
END
GO

--TABLA TIPO_VARIANTE
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_TIPO_VARIANTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.TIPO_VARIANTE
	ADD CONSTRAINT PK_TIPO_VARIANTE PRIMARY KEY (TIPO_VARIANTE_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.TIPO_VARIANTE agregada')
END
GO

--TABLA VENTA_POR_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VENTA_POR_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA_POR_PRODUCTO
	ADD CONSTRAINT PK_VENTA_POR_PRODUCTO PRIMARY KEY (VENTA_POR_PRODUCTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.VENTA_POR_PRODUCTO agregada')
END
GO

--TABLA VENTA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA
	ADD CONSTRAINT PK_VENTA PRIMARY KEY (VENTA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.VENTA agregada')
END
GO

--TABLA MARCA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MARCA')
BEGIN
	ALTER TABLE LOS_SELECTOS.MARCA
	ADD CONSTRAINT PK_MARCA PRIMARY KEY (MARCA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.MARCA agregada')
END
GO

--TABLA CATEGORIA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CATEGORIA')
BEGIN
	ALTER TABLE LOS_SELECTOS.CATEGORIA
	ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (CATEGORIA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.CATEGORIA agregada')
END
GO

--------------------------------------------------------
---------- CREACIÓN DE CONSTRAINTS DE TIPO FK ----------
--------------------------------------------------------

--TABLA LOCALIDAD
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE LOS_SELECTOS.LOCALIDAD
	ADD CONSTRAINT FK_LOCALIDAD_PROVINCIA FOREIGN KEY(LOCALIDAD_PROVINCIA_CODIGO) REFERENCES LOS_SELECTOS.PROVINCIA(PROVINCIA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.LOCALIDAD y LOS_SELECTOS.PROVINCIA agregada')
END
GO

--TABLA MEDIO_ENVIO_POR_LOCALIDAD
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD')
BEGIN
	ALTER TABLE LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD
	ADD CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_LOCALIDAD FOREIGN KEY(LOCALIDAD_CODIGO) REFERENCES LOS_SELECTOS.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD y LOS_SELECTOS.LOCALIDAD agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO')
BEGIN
	ALTER TABLE LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD
	ADD CONSTRAINT FK_MEDIO_ENVIO_POR_LOCALIDAD_MEDIO_ENVIO FOREIGN KEY(MEDIO_ENVIO_CODIGO) REFERENCES LOS_SELECTOS.MEDIO_ENVIO(MEDIO_ENVIO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD y LOS_SELECTOS.MEDIO_ENVIO agregada')
END
GO

--TABLA COMPRA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='UNACONST')
BEGIN
	ALTER TABLE LOS_SELECTOS.COMPRA
	ADD CONSTRAINT UNACONST FOREIGN KEY(COMPRA_MEDIO_DE_PAGO_CODIGO) REFERENCES LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA(MEDIO_DE_PAGO_COMPRA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.COMPRA y LOS_SELECTOS.MEDIO_DE_PAGO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_COMPRA_PROVEEDOR')
BEGIN
	ALTER TABLE LOS_SELECTOS.COMPRA
	ADD CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY(PROVEEDOR_CUIT) REFERENCES LOS_SELECTOS.PROVEEDOR(PROVEEDOR_CUIT)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.COMPRA y LOS_SELECTOS.PROVEEDOR agregada')
END
GO

--TABLA CUPON
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CUPON_CUPON_TIPO')
BEGIN
	ALTER TABLE LOS_SELECTOS.CUPON
	ADD CONSTRAINT FK_CUPON_CUPON_TIPO FOREIGN KEY(CUPON_TIPO_CODIGO) REFERENCES LOS_SELECTOS.CUPON_TIPO(CUPON_TIPO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.CUPON y LOS_SELECTOS.CUPON_TIPO agregada')
END
GO

--TABLA VENTA_POR_CUPON
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_CUPON')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA_POR_CUPON
	ADD CONSTRAINT FK_VENTA_POR_CUPON_CUPON FOREIGN KEY(CUPON_CODIGO) REFERENCES LOS_SELECTOS.CUPON(CUPON_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VENTA_POR_CUPON y LOS_SELECTOS.CUPON agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_CUPON_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA_POR_CUPON
	ADD CONSTRAINT FK_VENTA_POR_CUPON_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES LOS_SELECTOS.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VENTA_POR_CUPON y LOS_SELECTOS.VENTA agregada')
END
GO

--TABLA DESCUENTO_POR_VENTA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.DESCUENTO_POR_VENTA
	ADD CONSTRAINT FK_DESCUENTO_POR_VENTA_DESCUENTO_CONCEPTO FOREIGN KEY(DESCUENTO_CONCEPTO_CODIGO) REFERENCES LOS_SELECTOS.DESCUENTO_CONCEPTO(DESCUENTO_CONCEPTO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.DESCUENTO_POR_VENTA y LOS_SELECTOS.DESCUENTO_CONCEPTO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_POR_VENTA_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.DESCUENTO_POR_VENTA
	ADD CONSTRAINT FK_DESCUENTO_POR_VENTA_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES LOS_SELECTOS.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.DESCUENTO_POR_VENTA y LOS_SELECTOS.VENTA agregada')
END
GO

--TABLA DESCUENTO_COMPRA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DESCUENTO_COMPRA_COMPRA')
BEGIN
	ALTER TABLE LOS_SELECTOS.DESCUENTO_COMPRA
	ADD CONSTRAINT FK_DESCUENTO_COMPRA_COMPRA FOREIGN KEY(COMPRA_NUMERO) REFERENCES LOS_SELECTOS.COMPRA(COMPRA_NUMERO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.DESCUENTO_COMPRA y LOS_SELECTOS.COMPRA agregada')
END
GO

--TABLA COMPRA_POR_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_COMPRA')
BEGIN
	ALTER TABLE LOS_SELECTOS.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT FK_COMPRA_POR_PRODUCTO_COMPRA FOREIGN KEY(COMPRA_NUMERO) REFERENCES LOS_SELECTOS.COMPRA(COMPRA_NUMERO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.COMPRA_POR_PRODUCTO y LOS_SELECTOS.COMPRA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.COMPRA_POR_PRODUCTO
	ADD CONSTRAINT FK_COMPRA_POR_PRODUCTO_PRODUCTO_VARIANTE FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES LOS_SELECTOS.PRODUCTO_VARIANTE (PRODUCTO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.COMPRA_POR_PRODUCTO y LOS_SELECTOS.PRODUCTO_VARIANTE agregada')
END
GO

--TABLA PROVEEDOR
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
			   WHERE CONSTRAINT_NAME ='FK_PROVEEDOR_LOCALIDAD')
BEGIN
	ALTER TABLE LOS_SELECTOS.PROVEEDOR
	ADD CONSTRAINT FK_PROVEEDOR_LOCALIDAD FOREIGN KEY(PROVEEDOR_LOCALIDAD_CODIGO) REFERENCES LOS_SELECTOS.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.LOCALIDAD y LOS_SELECTOS.PROVEEDOR agregada')
END
GO

--TABLA CLIENTE
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_CLIENTE_LOCALIDAD')
BEGIN
	ALTER TABLE LOS_SELECTOS.CLIENTE
	ADD CONSTRAINT FK_CLIENTE_LOCALIDAD FOREIGN KEY(CLIENTE_LOCALIDAD_CODIGO) REFERENCES LOS_SELECTOS.LOCALIDAD(LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.CLIENTE y LOS_SELECTOS.LOCALIDAD agregada')
END
GO

--TABLA PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MARCA')
BEGIN
	ALTER TABLE LOS_SELECTOS.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY(PRODUCTO_MARCA_CODIGO) REFERENCES LOS_SELECTOS.MARCA(MARCA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.PRODUCTO y LOS_SELECTOS.MARCA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_CATEGORIA')
BEGIN
	ALTER TABLE LOS_SELECTOS.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY(PRODUCTO_CATEGORIA_CODIGO) REFERENCES LOS_SELECTOS.CATEGORIA(CATEGORIA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.PRODUCTO y LOS_SELECTOS.CATEGORIA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_MATERIAL')
BEGIN
	ALTER TABLE LOS_SELECTOS.PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_MATERIAL FOREIGN KEY(PRODUCTO_MATERIAL_CODIGO) REFERENCES LOS_SELECTOS.MATERIAL(MATERIAL_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.PRODUCTO y LOS_SELECTOS.MATERIAL agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.PRODUCTO_VARIANTE
	ADD CONSTRAINT FK_PRODUCTO_VARIANTE_PRODUCTO FOREIGN KEY(PRODUCTO_CODIGO) REFERENCES LOS_SELECTOS.PRODUCTO(PRODUCTO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.PRODUCTO_VARIANTE y LOS_SELECTOS.PRODUCTO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PRODUCTO_VARIANTE_VARIANTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.PRODUCTO_VARIANTE
	ADD CONSTRAINT FK_PRODUCTO_VARIANTE_VARIANTE FOREIGN KEY(VARIANTE_CODIGO) REFERENCES LOS_SELECTOS.VARIANTE(VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.PRODUCTO_VARIANTE y LOS_SELECTOS.VARIANTE agregada')
END
GO

--TABLA VARIANTE
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VARIANTE_TIPO_VARIANTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.VARIANTE
	ADD CONSTRAINT FK_VARIANTE_TIPO_VARIANTE FOREIGN KEY(VARIANTE_TIPO_VARIANTE_CODIGO) REFERENCES LOS_SELECTOS.TIPO_VARIANTE(TIPO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VARIANTE y LOS_SELECTOS.TIPO_VARIANTE agregada')
END
GO

--TABLA VENTA_POR_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA_POR_PRODUCTO
	ADD CONSTRAINT FK_VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES LOS_SELECTOS.PRODUCTO_VARIANTE(PRODUCTO_VARIANTE_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VENTA_POR_PRODUCTO y LOS_SELECTOS.PRODUCTO_VARIANTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_POR_PRODUCTO_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA_POR_PRODUCTO
	ADD CONSTRAINT FK_VENTA_POR_PRODUCTO_VENTA FOREIGN KEY(VENTA_CODIGO) REFERENCES LOS_SELECTOS.VENTA(VENTA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VENTA_POR_PRODUCTO y LOS_SELECTOS.VENTA agregada')
END
GO

--TABLA VENTA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CANAL')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA
	ADD CONSTRAINT FK_VENTA_CANAL FOREIGN KEY(VENTA_CANAL_CODIGO) REFERENCES LOS_SELECTOS.CANAL(CANAL_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VENTA y LOS_SELECTOS.CANAL agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_DE_PAGO_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA
	ADD CONSTRAINT FK_VENTA_MEDIO_DE_PAGO_VENTA FOREIGN KEY(VENTA_MEDIO_DE_PAGO_CODIGO) REFERENCES LOS_SELECTOS.MEDIO_DE_PAGO_VENTA(MEDIO_DE_PAGO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VENTA y LOS_SELECTOS.MEDIO_DE_PAGO_VENTA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_CLIENTE')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA
	ADD CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY(VENTA_CLIENTE_CODIGO) REFERENCES LOS_SELECTOS.CLIENTE(CLIENTE_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VENTA y LOS_SELECTOS.CLIENTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD')
BEGIN
	ALTER TABLE LOS_SELECTOS.VENTA
	ADD CONSTRAINT FK_VENTA_MEDIO_ENVIO_POR_LOCALIDAD FOREIGN KEY(VENTA_CANAL_CODIGO) REFERENCES LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD(MEDIO_ENVIO_POR_LOCALIDAD_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.VENTA y LOS_SELECTOS.LOCALIDAD agregada')
END
GO

--------------------------------------------
---------- CREACIÓN DE PROCEDURES ----------
--------------------------------------------


CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_VARIANTE
AS
BEGIN
	INSERT INTO LOS_SELECTOS.VARIANTE (VARIANTE_TIPO_VARIANTE_CODIGO,VARIANTE_NOMBRE )
		SELECT DISTINCT T.TIPO_VARIANTE_CODIGO,PRODUCTO_VARIANTE
		FROM  gd_esquema.Maestra M JOIN LOS_SELECTOS.TIPO_VARIANTE T ON M.PRODUCTO_TIPO_VARIANTE = T.TIPO_VARIANTE_VALOR WHERE PRODUCTO_VARIANTE IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.VARIANTE)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.VARIANTE. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_TIPO_VARIANTE
AS
BEGIN
	INSERT INTO LOS_SELECTOS.TIPO_VARIANTE (TIPO_VARIANTE_VALOR)
		SELECT DISTINCT PRODUCTO_TIPO_VARIANTE AS TIPO_VARIANTE_VALOR
		FROM gd_esquema.Maestra WHERE PRODUCTO_TIPO_VARIANTE IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.TIPO_VARIANTE)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.TIPO_VARIANTE. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_MARCA
AS
BEGIN
	INSERT INTO LOS_SELECTOS.MARCA (MARCA_NOMBRE)
		SELECT DISTINCT PRODUCTO_MARCA AS MARCA_NOMBRE
		FROM gd_esquema.Maestra WHERE PRODUCTO_MARCA IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.MARCA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.MARCA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_PROVINCIA
AS
BEGIN
	INSERT INTO LOS_SELECTOS.PROVINCIA (PROVINCIA_NOMBRE)
		SELECT DISTINCT CLIENTE_PROVINCIA
		FROM GD_ESQUEMA.MAESTRA
		WHERE CLIENTE_PROVINCIA IS NOT NULL
		UNION SELECT DISTINCT PROVEEDOR_PROVINCIA
			FROM GD_ESQUEMA.MAESTRA
			WHERE PROVEEDOR_PROVINCIA IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.PROVINCIA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.PROVINCIA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_LOCALIDAD
AS
BEGIN 
	INSERT INTO LOS_SELECTOS.LOCALIDAD (LOCALIDAD_PROVINCIA_CODIGO, LOCALIDAD_NOMBRE, LOCALIDAD_CODIGO_POSTAL)
		SELECT DISTINCT P.PROVINCIA_CODIGO, MA.CLIENTE_LOCALIDAD, MA.CLIENTE_CODIGO_POSTAL
		FROM gd_esquema.Maestra MA JOIN LOS_SELECTOS.PROVINCIA P ON MA.CLIENTE_PROVINCIA = P.PROVINCIA_NOMBRE
		UNION
			SELECT DISTINCT P.PROVINCIA_CODIGO, MA.PROVEEDOR_LOCALIDAD, MA.PROVEEDOR_CODIGO_POSTAL
			FROM gd_esquema.Maestra MA JOIN LOS_SELECTOS.PROVINCIA P ON MA.PROVEEDOR_PROVINCIA = P.PROVINCIA_NOMBRE
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.LOCALIDAD)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.LOCALIDAD. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_CLIENTE
AS
BEGIN 
	INSERT INTO LOS_SELECTOS.CLIENTE (CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, CLIENTE_LOCALIDAD_CODIGO)
		SELECT DISTINCT CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, L.LOCALIDAD_CODIGO
		FROM GD_ESQUEMA.MAESTRA MA JOIN LOS_SELECTOS.LOCALIDAD L ON MA.CLIENTE_LOCALIDAD = L.LOCALIDAD_NOMBRE AND MA.CLIENTE_CODIGO_POSTAL = L.LOCALIDAD_CODIGO_POSTAL
		WHERE CLIENTE_NOMBRE IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.CLIENTE)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.CLIENTE. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_PROVEEDOR
AS
BEGIN 
	INSERT INTO LOS_SELECTOS.PROVEEDOR (PROVEEDOR_CUIT, PROVEEDOR_LOCALIDAD_CODIGO, PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL)
		SELECT DISTINCT PROVEEDOR_CUIT, L.LOCALIDAD_CODIGO, PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL
		FROM GD_ESQUEMA.MAESTRA MA JOIN LOS_SELECTOS.LOCALIDAD L ON MA.PROVEEDOR_LOCALIDAD = L.LOCALIDAD_NOMBRE AND MA.PROVEEDOR_CODIGO_POSTAL = L.LOCALIDAD_CODIGO_POSTAL
		WHERE PROVEEDOR_CUIT IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.PROVEEDOR)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.PROVEEDOR. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_COMPRA
AS
BEGIN 
	INSERT INTO LOS_SELECTOS.COMPRA (COMPRA_NUMERO, COMPRA_MEDIO_DE_PAGO_CODIGO, PROVEEDOR_CUIT, COMPRA_FECHA, COMPRA_TOTAL)
		SELECT DISTINCT COMPRA_NUMERO, MPC.MEDIO_DE_PAGO_COMPRA_CODIGO, PROVEEDOR_CUIT, COMPRA_FECHA, COMPRA_TOTAL
		FROM GD_ESQUEMA.MAESTRA MA JOIN LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA MPC ON MA.COMPRA_MEDIO_PAGO = MPC.MEDIO_DE_PAGO_COMPRA_NOMBRE
		WHERE COMPRA_NUMERO IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.COMPRA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.COMPRA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_CATEGORIA
AS
BEGIN
	INSERT INTO LOS_SELECTOS.CATEGORIA (CATEGORIA_NOMBRE)
		SELECT DISTINCT PRODUCTO_CATEGORIA AS CATEGORIA_NOMBRE
		FROM gd_esquema.Maestra WHERE PRODUCTO_CATEGORIA IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.CATEGORIA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.MARCA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_CUPON_TIPO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.CUPON_TIPO (CUPON_TIPO_NOMBRE)
		SELECT DISTINCT M.VENTA_CUPON_TIPO
		FROM gd_esquema.Maestra M WHERE M.VENTA_CUPON_TIPO IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.CUPON_TIPO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.CUPON_TIPO. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_MATERIAL
AS
BEGIN
	INSERT INTO LOS_SELECTOS.MATERIAL (MATERIAL_NOMBRE)
		SELECT DISTINCT PRODUCTO_MATERIAL AS MATERIAL_NOMBRE
		FROM gd_esquema.Maestra WHERE PRODUCTO_MATERIAL IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.MATERIAL)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.MATERIAL. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_CUPON
AS
BEGIN
	INSERT INTO LOS_SELECTOS.CUPON (CUPON_CODIGO, CUPON_TIPO_CODIGO, CUPON_FECHA_DESDE, CUPON_FECHA_HASTA, CUPON_VALOR)
		SELECT DISTINCT 
			M.VENTA_CUPON_CODIGO CUPON_CODIGO,
			CT.CUPON_TIPO_CODIGO CUPON_TIPO_CODIGO,
			M.VENTA_CUPON_FECHA_DESDE CUPON_FECHA_DESDE,
			M.VENTA_CUPON_FECHA_HASTA CUPON_FECHA_HASTA,
			M.VENTA_CUPON_VALOR CUPON_VALOR
		FROM gd_esquema.Maestra M
		JOIN LOS_SELECTOS.CUPON_TIPO CT on CT.CUPON_TIPO_NOMBRE = M.VENTA_CUPON_TIPO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.CUPON)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.CUPON. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_PRODUCTO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.PRODUCTO
		SELECT DISTINCT MA.PRODUCTO_CODIGO AS PRODUCTO_CODIGO,
			M.MARCA_CODIGO AS PRODUCTO_MARCA_CODIGO,MT.MATERIAL_CODIGO AS  PRODUCTO_MATERIAL_CODIGO ,
			CA.CATEGORIA_CODIGO AS  PRODUCTO_CATEGORIA_CODIGO ,
			MA.PRODUCTO_NOMBRE AS PRODUCTO_NOMBRE, MA.PRODUCTO_DESCRIPCION AS  PRODUCTO_DESCRIPCION
		FROM gd_esquema.Maestra MA JOIN LOS_SELECTOS.MARCA M ON MA.PRODUCTO_MARCA = M.MARCA_NOMBRE 
		JOIN LOS_SELECTOS.MATERIAL MT ON MA.PRODUCTO_MATERIAL = MT.MATERIAL_NOMBRE 
		JOIN LOS_SELECTOS.CATEGORIA CA ON MA.PRODUCTO_CATEGORIA = CA.CATEGORIA_NOMBRE 
		WHERE PRODUCTO_CODIGO IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.PRODUCTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.PRODUCTO. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_VENTA_POR_CUPON
AS
BEGIN
	INSERT INTO LOS_SELECTOS.VENTA_POR_CUPON (CUPON_CODIGO, VENTA_CODIGO, CUPON_IMPORTE)
		SELECT DISTINCT 
			M.VENTA_CUPON_CODIGO,
			M.VENTA_CODIGO,
			M.VENTA_CUPON_IMPORTE
		FROM gd_esquema.Maestra M
		WHERE M.VENTA_CUPON_CODIGO IS NOT NULL AND M.VENTA_CODIGO IS NOT NULL AND M.VENTA_CUPON_IMPORTE IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.VENTA_POR_CUPON)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.VENTA_POR_CUPON. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_PRODUCTO_VARIANTE
AS
BEGIN
	INSERT INTO LOS_SELECTOS.PRODUCTO_VARIANTE
		SELECT DISTINCT MA.PRODUCTO_VARIANTE_CODIGO AS PRODUCTO_VARIANTE_CODIGO,
			P.PRODUCTO_CODIGO AS PRODUCTO_CODIGO,V.VARIANTE_CODIGO AS  VARIANTE_CODIGO ,
			max(COMPRA_PRODUCTO_PRECIO) AS PRECIO_ACTUAL_COMPRA,
			max(VENTA_PRODUCTO_PRECIO) AS PRECIO_ACTUAL_VENTA
		FROM gd_esquema.Maestra MA JOIN LOS_SELECTOS.PRODUCTO P ON MA.PRODUCTO_CODIGO = P.PRODUCTO_CODIGO 
		JOIN LOS_SELECTOS.VARIANTE V ON V.VARIANTE_NOMBRE = MA.PRODUCTO_VARIANTE 
		WHERE PRODUCTO_VARIANTE_CODIGO IS NOT NULL
		GROUP BY PRODUCTO_VARIANTE_CODIGO ,P.PRODUCTO_CODIGO,V.VARIANTE_CODIGO
		ORDER BY PRODUCTO_VARIANTE_CODIGO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.PRODUCTO_VARIANTE)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.PRODUCTO_VARIANTE. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_CANAL
AS
BEGIN
	INSERT INTO LOS_SELECTOS.CANAL (CANAL_NOMBRE, CANAL_COSTO)
		SELECT DISTINCT 
			M.VENTA_CANAL,
			M.VENTA_CANAL_COSTO
		FROM gd_esquema.Maestra M
		WHERE M.VENTA_CANAL IS NOT NULL AND M.VENTA_CANAL_COSTO IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.CANAL)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.CANAL. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_VENTA_POR_PRODUCTO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.VENTA_POR_PRODUCTO (PRODUCTO_VARIANTE_CODIGO, VENTA_CODIGO, PRODUCTO_CANTIDAD, PRODUCTO_PRECIO_TOTAL)
		SELECT  P.PRODUCTO_VARIANTE_CODIGO AS PRODUCTO_VARIANTE_CODIGO,
			V.VENTA_CODIGO AS VENTA_CODIGO, 
			MA.VENTA_PRODUCTO_CANTIDAD AS PRODUCTO_CANTIDAD,
			MA.VENTA_PRODUCTO_CANTIDAD*MA.VENTA_PRODUCTO_PRECIO AS PRODUCTO_PRECIO_TOTAL
		FROM gd_esquema.Maestra MA JOIN LOS_SELECTOS.VENTA V ON MA.VENTA_CODIGO = V.VENTA_CODIGO 
		JOIN LOS_SELECTOS.PRODUCTO_VARIANTE P ON P.PRODUCTO_VARIANTE_CODIGO = MA.PRODUCTO_VARIANTE_CODIGO 
		ORDER BY VENTA_CODIGO,PRODUCTO_VARIANTE_CODIGO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.VENTA_POR_PRODUCTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.VENTA_POR_PRODUCTO. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_DESCUENTO_POR_VENTA
AS
BEGIN
	INSERT INTO LOS_SELECTOS.DESCUENTO_POR_VENTA (DESCUENTO_CONCEPTO_CODIGO, VENTA_CODIGO, DESCUENTO_IMPORTE)
		SELECT DISTINCT 
			DC.DESCUENTO_CONCEPTO_CODIGO,
			M.VENTA_CODIGO,
			M.VENTA_DESCUENTO_IMPORTE
		FROM gd_esquema.Maestra M
		JOIN LOS_SELECTOS.DESCUENTO_CONCEPTO DC on DC.DESCUENTO_CONCEPTO_NOMBRE= M.VENTA_DESCUENTO_CONCEPTO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.DESCUENTO_POR_VENTA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.DESCUENTO_POR_VENTA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_DESCUENTO_CONCEPTO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.DESCUENTO_CONCEPTO (DESCUENTO_CONCEPTO_NOMBRE)
		SELECT DISTINCT 
			M.VENTA_DESCUENTO_CONCEPTO
		FROM gd_esquema.Maestra M
		WHERE M.VENTA_DESCUENTO_CONCEPTO IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.DESCUENTO_CONCEPTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.DESCUENTO_CONCEPTO. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO


CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_MEDIO_DE_PAGO_VENTA
AS
BEGIN
	INSERT INTO LOS_SELECTOS.MEDIO_DE_PAGO_VENTA (MEDIO_DE_PAGO_NOMBRE, MEDIO_DE_PAGO_COSTO)
		SELECT DISTINCT VENTA_MEDIO_PAGO, VENTA_MEDIO_PAGO_COSTO
		FROM GD_ESQUEMA.MAESTRA
		WHERE VENTA_MEDIO_PAGO IS NOT NULL AND VENTA_MEDIO_PAGO_COSTO IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.MEDIO_DE_PAGO_VENTA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.MEDIO_DE_PAGO_VENTA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_VENTA
AS
BEGIN 
	INSERT INTO LOS_SELECTOS.VENTA (VENTA_CODIGO, VENTA_CANAL_CODIGO, VENTA_MEDIO_DE_PAGO_CODIGO, VENTA_CLIENTE_CODIGO, VENTA_MEDIO_ENVIO_POR_LOCALIDAD_CODIGO, VENTA_FECHA, VENTA_TOTAL)
		SELECT DISTINCT
			M.VENTA_CODIGO,
			C.CANAL_CODIGO VENTA_CANAL_CODIGO,
			MPV.MEDIO_DE_PAGO_CODIGO VENTA_MEDIO_DE_PAGO_CODIGO,
			CL.CLIENTE_CODIGO VENTA_CLIENTE_CODIGO,
			MEPC.MEDIO_ENVIO_POR_LOCALIDAD_CODIGO VENTA_MEDIO_ENVIO_POR_LOCALIDAD_CODIGO,
			M.VENTA_FECHA,
			M.VENTA_TOTAL
		FROM gd_esquema.Maestra M
		JOIN LOS_SELECTOS.CANAL C on C.CANAL_NOMBRE = M.VENTA_CANAL 
		JOIN LOS_SELECTOS.MEDIO_DE_PAGO_VENTA MPV on MPV.MEDIO_DE_PAGO_NOMBRE = M.VENTA_MEDIO_PAGO
		JOIN LOS_SELECTOS.CLIENTE CL on CL.CLIENTE_DNI = M.CLIENTE_DNI AND CL.CLIENTE_APELLIDO = M.CLIENTE_APELLIDO
		JOIN LOS_SELECTOS.LOCALIDAD L on L.LOCALIDAD_NOMBRE = M.CLIENTE_LOCALIDAD AND L.LOCALIDAD_CODIGO_POSTAL = M.CLIENTE_CODIGO_POSTAL
		JOIN LOS_SELECTOS.MEDIO_ENVIO ME on ME.MEDIO_ENVIO_NOMBRE = M.VENTA_MEDIO_ENVIO
		JOIN LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD MEPC on MEPC.LOCALIDAD_CODIGO = L.LOCALIDAD_CODIGO AND MEPC.MEDIO_ENVIO_CODIGO = ME.MEDIO_ENVIO_CODIGO
		WHERE M.VENTA_CODIGO IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.VENTA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.VENTA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_MEDIO_ENVIO
AS
BEGIN 
	INSERT INTO LOS_SELECTOS.MEDIO_ENVIO (MEDIO_ENVIO_NOMBRE)
		SELECT DISTINCT
			M.VENTA_MEDIO_ENVIO MEDIO_ENVIO_NOMBRE
		FROM gd_esquema.Maestra M
		WHERE M.VENTA_MEDIO_ENVIO IS NOT NULL 
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.MEDIO_ENVIO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.MEDIO_ENVIO. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_MEDIO_DE_PAGO_COMPRA
AS
BEGIN 
	INSERT INTO LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA (MEDIO_DE_PAGO_COMPRA_NOMBRE)
		SELECT DISTINCT 
			M.COMPRA_MEDIO_PAGO MEDIO_DE_PAGO_COMPRA_NOMBRE
		FROM gd_esquema.Maestra M
		WHERE M.COMPRA_MEDIO_PAGO IS NOT NULL 
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.MEDIO_DE_PAGO_COMPRA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_DESCUENTO_COMPRA
AS
BEGIN 
	INSERT INTO LOS_SELECTOS.DESCUENTO_COMPRA (DESCUENTO_COMPRA_CODIGO, COMPRA_NUMERO, DESCUENTO_COMPRA_VALOR)
		SELECT DISTINCT 
			M.DESCUENTO_COMPRA_CODIGO,
			M.COMPRA_NUMERO,
			M.DESCUENTO_COMPRA_VALOR 
		FROM gd_esquema.Maestra M
		WHERE DESCUENTO_COMPRA_CODIGO IS NOT NULL AND COMPRA_NUMERO IS NOT NULL AND DESCUENTO_COMPRA_VALOR IS NOT NULL
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.DESCUENTO_COMPRA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.DESCUENTO_COMPRA. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_COMPRA_POR_PRODUCTO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.COMPRA_POR_PRODUCTO (COMPRA_NUMERO, PRODUCTO_VARIANTE_CODIGO, PRODUCTO_CANTIDAD,PRODUCTO_PRECIO_TOTAL)
		SELECT  C.COMPRA_NUMERO AS COMPRA_NUMERO,
			PV.PRODUCTO_VARIANTE_CODIGO AS PRODUCTO_VARIANTE_CODIGO,
			MA.COMPRA_PRODUCTO_CANTIDAD AS PRODUCTO_CANTIDAD,
			MA.COMPRA_PRODUCTO_CANTIDAD*MA.COMPRA_PRODUCTO_PRECIO AS PRODUCTO_PRECIO_TOTAL
		FROM gd_esquema.Maestra MA JOIN LOS_SELECTOS.COMPRA C ON MA.COMPRA_NUMERO = C.COMPRA_NUMERO 
		JOIN LOS_SELECTOS.PRODUCTO_VARIANTE PV ON PV.PRODUCTO_VARIANTE_CODIGO = MA.PRODUCTO_VARIANTE_CODIGO 
		ORDER BY COMPRA_NUMERO,PRODUCTO_VARIANTE_CODIGO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.COMPRA_POR_PRODUCTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.COMPRA_POR_PRODUCTO. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_MEDIO_ENVIO_POR_LOCALIDAD
AS
BEGIN
	INSERT INTO LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD (LOCALIDAD_CODIGO, MEDIO_ENVIO_CODIGO, VENTA_ENVIO_PRECIO)
		SELECT DISTINCT 
			L.LOCALIDAD_CODIGO,
			ME.MEDIO_ENVIO_CODIGO,
			M.VENTA_ENVIO_PRECIO
		FROM gd_esquema.Maestra M
		JOIN LOS_SELECTOS.LOCALIDAD L ON L.LOCALIDAD_NOMBRE = M.CLIENTE_LOCALIDAD AND L.LOCALIDAD_CODIGO_POSTAL = M.CLIENTE_CODIGO_POSTAL
		JOIN LOS_SELECTOS.MEDIO_ENVIO ME ON ME.MEDIO_ENVIO_NOMBRE = M.VENTA_MEDIO_ENVIO
		WHERE M.VENTA_MEDIO_ENVIO IS NOT NULL 
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD. Nuevas filas: ' + @CANTIDAD_REGISTROS)
END
GO

---------------------------------------------
---------- EJECUCIÓN DE PROCEDURES ----------
---------------------------------------------

EXEC LOS_SELECTOS.MIGRAR_TABLA_CUPON_TIPO
EXEC LOS_SELECTOS.MIGRAR_TABLA_CUPON
EXEC LOS_SELECTOS.MIGRAR_TABLA_CANAL
EXEC LOS_SELECTOS.MIGRAR_TABLA_PROVINCIA
EXEC LOS_SELECTOS.MIGRAR_TABLA_LOCALIDAD
EXEC LOS_SELECTOS.MIGRAR_TABLA_PROVEEDOR
EXEC LOS_SELECTOS.MIGRAR_TABLA_CLIENTE
EXEC LOS_SELECTOS.MIGRAR_TABLA_MATERIAL
EXEC LOS_SELECTOS.MIGRAR_TABLA_MEDIO_DE_PAGO_COMPRA
EXEC LOS_SELECTOS.MIGRAR_TABLA_COMPRA
EXEC LOS_SELECTOS.MIGRAR_TABLA_MEDIO_ENVIO
EXEC LOS_SELECTOS.MIGRAR_TABLA_MEDIO_DE_PAGO_VENTA
EXEC LOS_SELECTOS.MIGRAR_TABLA_MEDIO_ENVIO_POR_LOCALIDAD
EXEC LOS_SELECTOS.MIGRAR_TABLA_VENTA
EXEC LOS_SELECTOS.MIGRAR_TABLA_VENTA_POR_CUPON
EXEC LOS_SELECTOS.MIGRAR_TABLA_DESCUENTO_COMPRA
EXEC LOS_SELECTOS.MIGRAR_TABLA_MARCA
EXEC LOS_SELECTOS.MIGRAR_TABLA_CATEGORIA
EXEC LOS_SELECTOS.MIGRAR_TABLA_TIPO_VARIANTE
EXEC LOS_SELECTOS.MIGRAR_TABLA_VARIANTE
EXEC LOS_SELECTOS.MIGRAR_TABLA_PRODUCTO
EXEC LOS_SELECTOS.MIGRAR_TABLA_PRODUCTO_VARIANTE
EXEC LOS_SELECTOS.MIGRAR_TABLA_COMPRA_POR_PRODUCTO
EXEC LOS_SELECTOS.MIGRAR_TABLA_DESCUENTO_CONCEPTO
EXEC LOS_SELECTOS.MIGRAR_TABLA_VENTA_POR_PRODUCTO
EXEC LOS_SELECTOS.MIGRAR_TABLA_DESCUENTO_POR_VENTA
