USE GD2C2022
GO

---------------------------------------------
---------- BORRADO DE FOREIGN KEYS ----------
---------------------------------------------

IF Object_id('LOS_SELECTOS.BI_BORRAR_FOREIGN_KEYS') IS NOT NULL
  DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_FOREIGN_KEYS
GO 

CREATE PROCEDURE LOS_SELECTOS.BI_BORRAR_FOREIGN_KEYS
AS
	DECLARE @query nvarchar(255)
	DECLARE query_cursor CURSOR FOR
		SELECT 'ALTER TABLE '
		+ object_schema_name(fk.parent_object_id)
		+ '.[' + Object_name(fk.parent_object_id)
		+ '] DROP CONSTRAINT ' + fk.name query
		FROM sys.foreign_keys fk
		WHERE  fk.name LIKE 'FK_BI%' 
	OPEN query_cursor
	FETCH NEXT FROM query_cursor INTO @query
	WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC sp_executesql
			@query
			FETCH NEXT FROM query_cursor INTO @query
		END
	CLOSE query_cursor
	DEALLOCATE query_cursor
GO

---------------------------------------------
------------- BORRADO DE TABLAS -------------
---------------------------------------------

IF Object_id('LOS_SELECTOS.BI_BORRAR_TABLAS') IS NOT NULL
	DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_TABLAS
GO

CREATE PROCEDURE LOS_SELECTOS.BI_BORRAR_TABLAS
AS
	DECLARE @query nvarchar(255)
	DECLARE query_cursor CURSOR FOR
	SELECT 'DROP TABLE LOS_SELECTOS.' + name
			FROM  sys.tables
			WHERE schema_id = (SELECT schema_id FROM sys.schemas WHERE name = 'LOS_SELECTOS') AND name like 'BI_%'
	OPEN query_cursor
	FETCH NEXT FROM query_cursor INTO @query
	WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC sp_executesql @query
			FETCH NEXT FROM query_cursor INTO @query
		END
	CLOSE query_cursor
	DEALLOCATE query_cursor
GO

---------------------------------------------
----------- BORRADO DE PROCEDURES -----------
---------------------------------------------

IF Object_id('LOS_SELECTOS.BI_BORRAR_PROCEDURES') IS NOT NULL
  DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_PROCEDURES
GO

CREATE PROCEDURE LOS_SELECTOS.BI_BORRAR_PROCEDURES
AS
	DECLARE @query nvarchar(255)
	DECLARE query_cursor CURSOR FOR
	SELECT 'DROP PROCEDURE LOS_SELECTOS.' + name
		FROM  sys.procedures
		WHERE schema_id = (SELECT schema_id FROM sys.schemas WHERE name = 'LOS_SELECTOS') AND name LIKE 'MIGRAR_TABLA_BI%'
	OPEN query_cursor
	FETCH NEXT FROM query_cursor INTO @query
	WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC sp_executesql @query
			FETCH NEXT FROM query_cursor INTO @query
		END
	CLOSE query_cursor
	DEALLOCATE query_cursor
GO

------------------------------------------
---------- BORRADO DE FUNCIONES ----------
------------------------------------------

IF Object_id('LOS_SELECTOS.BI_BORRAR_FUNCIONES') IS NOT NULL 
  DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_FUNCIONES
GO 

CREATE PROCEDURE LOS_SELECTOS.BI_BORRAR_FUNCIONES
AS
	DECLARE @query nvarchar(255) 
	DECLARE query_cursor CURSOR FOR  
	SELECT 'DROP FUNCTION LOS_SELECTOS.' + name
		FROM sys.sql_modules m
		INNER JOIN sys.objects o 
		ON m.object_id = o.object_id
		WHERE name like 'BI_FUNCION%'
	OPEN query_cursor 
	FETCH NEXT FROM query_cursor INTO @query
	WHILE @@FETCH_STATUS = 0 
		BEGIN
			EXEC sp_executesql
			@query
			FETCH NEXT FROM query_cursor INTO @query
		END
	CLOSE query_cursor
	DEALLOCATE query_cursor
GO 

---------------------------------------
---------- BORRADO DE VISTAS ----------
---------------------------------------

IF Object_id('LOS_SELECTOS.BI_BORRAR_VISTAS') IS NOT NULL 
  DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_VISTAS

GO 

CREATE PROCEDURE LOS_SELECTOS.BI_BORRAR_VISTAS
AS
	DECLARE @query nvarchar(255)
	DECLARE query_cursor CURSOR FOR
		SELECT 'DROP VIEW LOS_SELECTOS.' + name
		FROM sys.views
	OPEN query_cursor
	FETCH NEXT FROM query_cursor INTO @query
	WHILE @@FETCH_STATUS = 0
		BEGIN
			EXEC sp_executesql
			@query
			FETCH NEXT FROM query_cursor INTO @query
		END
		CLOSE query_cursor
		DEALLOCATE query_cursor
GO 


-------------------------------------------------------------------------------------
---------- BORRADO DE FOREIGN KEYS, TABLAS, PROCEDURES, FUNCIONES Y VISTAS ----------
-------------------------------------------------------------------------------------

EXEC LOS_SELECTOS.BI_BORRAR_FOREIGN_KEYS
EXEC LOS_SELECTOS.BI_BORRAR_TABLAS
EXEC LOS_SELECTOS.BI_BORRAR_PROCEDURES
EXEC LOS_SELECTOS.BI_BORRAR_FUNCIONES
EXEC LOS_SELECTOS.BI_BORRAR_VISTAS
GO

/*
DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_FOREIGN_KEYS
DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_TABLAS
DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_FUNCIONES
DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_PROCEDURES
DROP PROCEDURE LOS_SELECTOS.BI_BORRAR_VISTAS
GO
*/
-------------------------------------------
---------- CREACIÓN DE FUNCIONES ----------
-------------------------------------------

CREATE FUNCTION LOS_SELECTOS.BI_FUNCION_RANGO_ETARIO(@fecha_nac DATE) RETURNS NVARCHAR(15)
AS
BEGIN
	DECLARE @rango NVARCHAR(15)
	DECLARE @edad INT
	SELECT @edad = convert(int, DATEDIFF(d,@fecha_nac, getdate())/365.25)
	SELECT @rango = CASE 
		WHEN @edad < 25  THEN '<25'
		WHEN @edad >= 25 AND @edad < 35 THEN '25 - 35'
		WHEN @edad >= 35 AND @edad <= 55 THEN '35 - 55'
		ELSE '>55'
	END
	RETURN @rango
END
GO

----------------------------------------
---------- CREACIÓN DE TABLAS ----------
----------------------------------------

IF OBJECT_ID('LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO(
		HECHO_VENTA_PRODUCTO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
		EDAD_CODIGO decimal(19,0),
		TIEMPO_CODIGO decimal(19,0),
		PROVINCIA_CODIGO decimal(18,0),
		CANAL_CODIGO decimal(19,0),
		MEDIO_DE_PAGO_CODIGO decimal(19,0),
		CATEGORIA_CODIGO decimal(18,0),
		PRODUCTO_CODIGO nvarchar(50),
		MEDIO_ENVIO_CODIGO decimal(19,0),
		ENVIO_PRECIO_MES_PROV_MDE decimal(18,2),
		CANT_ENVIO_MES_PROV_MDE decimal(18,2),
		CANT_ENVIO_MES_MDP_CV  decimal(18,2),
		PRODUCTO_PRECIO_TOTAL decimal(18,2)
	)
	PRINT('Tabla LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_PROVINCIA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_PROVINCIA(
		PROVINCIA_CODIGO decimal(18,0) not null,
		PROVINCIA_NOMBRE nvarchar(255)
	)
	PRINT('Tabla LOS_SELECTOS.BI_PROVINCIA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_MEDIO_DE_PAGO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_MEDIO_DE_PAGO(
		MEDIO_DE_PAGO_CODIGO decimal(19,0) not null,
		MEDIO_DE_PAGO_NOMBRE nvarchar(255),
		MEDIO_DE_PAGO_COSTO decimal(19,2)
	)
	PRINT('Tabla LOS_SELECTOS.BI_MEDIO_DE_PAGO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_MEDIO_DE_ENVIO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_MEDIO_DE_ENVIO(
		MEDIO_ENVIO_CODIGO decimal(19,0) not null,
		MEDIO_ENVIO_NOMBRE nvarchar(255),
	)
	PRINT('Tabla LOS_SELECTOS.BI_MEDIO_DE_ENVIO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_TIPO_DE_DESCUENTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_TIPO_DE_DESCUENTO(
		TIPO_DESCUENTO_CODIGO decimal(19,0) not null,
		TIPO_DESCUENTO_NOMBRE nvarchar(50),
	)
	PRINT('Tabla LOS_SELECTOS.BI_TIPO_DE_DESCUENTO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_TIEMPO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_TIEMPO(
		TIEMPO_CODIGO DECIMAL(19,0) NOT NULL IDENTITY(1,1),
		TIEMPO_ANIO INT,
		TIEMPO_MES INT,
	)
	PRINT('Tabla LOS_SELECTOS.BI_TIEMPO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_RANGO_EDAD', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_RANGO_EDAD(
		EDAD_CODIGO DECIMAL(19,0) NOT NULL IDENTITY(1,1),
		EDAD_CATEGORIA NVARCHAR(15)
	)
	PRINT('Tabla LOS_SELECTOS.BI_RANGO_EDAD creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO(
		BI_HECHO_COMPRA_PRODUCTO_CODIGO decimal(19,0) NOT NULL IDENTITY(1,1),
		PROVEEDOR_CUIT NVARCHAR(50),
		TIEMPO_CODIGO decimal(19,0),
		PRODUCTO_CODIGO nvarchar(50),
		PRODUCTO_CANTIDAD decimal(18,0),
		PRODUCTO_PRECIO_UNITARIO decimal(18,2),
	)
	PRINT('Tabla LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_CATEGORIA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_CATEGORIA(
		CATEGORIA_CODIGO decimal(18,0) not null,
		CATEGORIA_NOMBRE nvarchar(255)
	)
	PRINT('Tabla LOS_SELECTOS.BI_CATEGORIA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_PRODUCTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_PRODUCTO(
		PRODUCTO_CODIGO nvarchar(50) not null,
		PRODUCTO_NOMBRE nvarchar(50)
	)
	PRINT('Tabla LOS_SELECTOS.BI_PRODUCTO creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_CANAL_VENTA', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_CANAL_VENTA(
		CANAL_CODIGO decimal(19,0) not null,
		CANAL_NOMBRE nvarchar(255),
		CANAL_COSTO decimal(18,2)
	)
	PRINT('Tabla LOS_SELECTOS.BI_CANAL_VENTA creada')
END
GO

IF OBJECT_ID('LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO', 'U') IS NULL
BEGIN
	CREATE TABLE LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO(
		BI_HECHO_VENTA_DESCUENTO_CODIGO decimal(19,0) not null IDENTITY(1,1),
		TIPO_DESCUENTO_CODIGO decimal(19,0) not null,
		TIEMPO_CODIGO decimal(19,0),
		CANAL_CODIGO decimal(19,0),
		MEDIO_DE_PAGO_CODIGO decimal(19,0),
		DESCUENTO_IMPORTE decimal(18,2)
	)
PRINT('Tabla LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO creada')
END
GO

--------------------------------------------------------
---------- CREACIÓN DE CONSTRAINTS DE TIPO PK ----------
--------------------------------------------------------

--TABLA BI_HECHO_VENTA_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_HECHO_VENTA_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT PK_BI_HECHO_VENTA_PRODUCTO PRIMARY KEY (HECHO_VENTA_PRODUCTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO agregada')
END
GO

--TABLA BI_PROVINCIA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_PROVINCIA')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_PROVINCIA
	ADD CONSTRAINT PK_BI_PROVINCIA PRIMARY KEY (PROVINCIA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_PROVINCIA agregada')
END
GO

--TABLA BI_MEDIO_DE_PAGO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_MEDIO_DE_PAGO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_MEDIO_DE_PAGO
	ADD CONSTRAINT PK_BI_MEDIO_DE_PAGO PRIMARY KEY (MEDIO_DE_PAGO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_MEDIO_DE_PAGO agregada')
END
GO

--TABLA BI_MEDIO_DE_ENVIO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_MEDIO_DE_ENVIO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_MEDIO_DE_ENVIO
	ADD CONSTRAINT PK_BI_MEDIO_DE_ENVIO PRIMARY KEY (MEDIO_ENVIO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_MEDIO_DE_ENVIO agregada')
END
GO

--TABLA BI_TIPO_DE_DESCUENTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_TIPO_DE_DESCUENTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_TIPO_DE_DESCUENTO
	ADD CONSTRAINT PK_BI_TIPO_DE_DESCUENTO PRIMARY KEY (TIPO_DESCUENTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_TIPO_DE_DESCUENTO agregada')
END
GO

--TABLA BI_TIEMPO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_TIEMPO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_TIEMPO
	ADD CONSTRAINT PK_BI_TIEMPO PRIMARY KEY (TIEMPO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_TIEMPO agregada')
END
GO

--TABLA BI_RANGO_EDAD
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_RANGO_EDAD')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_RANGO_EDAD
	ADD CONSTRAINT PK_BI_RANGO_EDAD PRIMARY KEY (EDAD_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_RANGO_EDAD agregada')
END
GO

--TABLA BI_HECHO_COMPRA_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_HECHO_COMPRA_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO
	ADD CONSTRAINT PK_BI_HECHO_COMPRA_PRODUCTO PRIMARY KEY (BI_HECHO_COMPRA_PRODUCTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO agregada')
END
GO

--TABLA BI_CATEGORIA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_CATEGORIA')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_CATEGORIA
	ADD CONSTRAINT PK_BI_CATEGORIA PRIMARY KEY (CATEGORIA_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_CATEGORIA agregada')
END
GO

--TABLA BI_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_PRODUCTO
	ADD CONSTRAINT PK_BI_PRODUCTO PRIMARY KEY (PRODUCTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_PRODUCTO agregada')
END
GO

--TABLA BI_CANAL_VENTA
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_CANAL_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_CANAL_VENTA
	ADD CONSTRAINT PK_BI_CANAL_VENTA PRIMARY KEY (CANAL_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_CANAL_VENTA agregada')
END
GO

--TABLA BI_HECHO_VENTA_DESCUENTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_HECHO_VENTA_DESCUENTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO
	ADD CONSTRAINT PK_BI_HECHO_VENTA_DESCUENTO PRIMARY KEY (BI_HECHO_VENTA_DESCUENTO_CODIGO)
	PRINT('Primary key de la tabla LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO agregada')
END
GO

--------------------------------------------------------
---------- CREACIÓN DE CONSTRAINTS DE TIPO FK ----------
--------------------------------------------------------

--TABLA BI_HECHO_VENTA_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_PRODUCTO_BI_RANGO_EDAD')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_PRODUCTO_BI_RANGO_EDAD FOREIGN KEY(EDAD_CODIGO) REFERENCES LOS_SELECTOS.BI_RANGO_EDAD(EDAD_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO y LOS_SELECTOS.BI_RANGO_EDAD agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_PRODUCTO_BI_TIEMPO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_PRODUCTO_BI_TIEMPO FOREIGN KEY(TIEMPO_CODIGO) REFERENCES LOS_SELECTOS.BI_TIEMPO(TIEMPO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO y LOS_SELECTOS.BI_TIEMPO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_PRODUCTO_BI_PROVINCIA')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_PRODUCTO_BI_PROVINCIA FOREIGN KEY(PROVINCIA_CODIGO) REFERENCES LOS_SELECTOS.BI_PROVINCIA(PROVINCIA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO y LOS_SELECTOS.BI_PROVINCIA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_PRODUCTO_BI_CANAL_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_PRODUCTO_BI_CANAL_VENTA FOREIGN KEY(CANAL_CODIGO) REFERENCES LOS_SELECTOS.BI_CANAL_VENTA(CANAL_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO y LOS_SELECTOS.BI_CANAL_VENTA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_PRODUCTO_BI_MEDIO_DE_PAGO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_PRODUCTO_BI_MEDIO_DE_PAGO FOREIGN KEY(MEDIO_DE_PAGO_CODIGO) REFERENCES LOS_SELECTOS.BI_MEDIO_DE_PAGO(MEDIO_DE_PAGO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO y LOS_SELECTOS.BI_MEDIO_DE_PAGO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_PRODUCTO_BI_CATEGORIA')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_PRODUCTO_BI_CATEGORIA FOREIGN KEY(CATEGORIA_CODIGO) REFERENCES LOS_SELECTOS.BI_CATEGORIA(CATEGORIA_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO y LOS_SELECTOS.BI_CATEGORIA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_PRODUCTO_BI_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_PRODUCTO_BI_PRODUCTO FOREIGN KEY(PRODUCTO_CODIGO) REFERENCES LOS_SELECTOS.BI_PRODUCTO(PRODUCTO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO y LOS_SELECTOS.BI_PRODUCTO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_PRODUCTO_BI_MEDIO_DE_ENVIO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_PRODUCTO_BI_MEDIO_DE_ENVIO FOREIGN KEY(MEDIO_ENVIO_CODIGO) REFERENCES LOS_SELECTOS.BI_MEDIO_DE_ENVIO(MEDIO_ENVIO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO y LOS_SELECTOS.BI_MEDIO_DE_ENVIO agregada')
END
GO

--TABLA BI_HECHO_COMPRA_PRODUCTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_COMPRA_PRODUCTO_BI_TIEMPO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_COMPRA_PRODUCTO_BI_TIEMPO FOREIGN KEY(TIEMPO_CODIGO) REFERENCES LOS_SELECTOS.BI_TIEMPO(TIEMPO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO y LOS_SELECTOS.BI_TIEMPO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_COMPRA_PRODUCTO_BI_PRODUCTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO
	ADD CONSTRAINT FK_BI_HECHO_COMPRA_PRODUCTO_BI_PRODUCTO FOREIGN KEY(PRODUCTO_CODIGO) REFERENCES LOS_SELECTOS.BI_PRODUCTO(PRODUCTO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO y LOS_SELECTOS.BI_PRODUCTO agregada')
END
GO

--TABLA BI_HECHO_VENTA_DESCUENTO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_DESCUENTO_BI_TIPO_DE_DESCUENTO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_DESCUENTO_BI_TIPO_DE_DESCUENTO FOREIGN KEY(TIPO_DESCUENTO_CODIGO) REFERENCES LOS_SELECTOS.BI_TIPO_DE_DESCUENTO(TIPO_DESCUENTO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO y LOS_SELECTOS.BI_TIPO_DE_DESCUENTO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_DESCUENTO_BI_TIEMPO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_DESCUENTO_BI_TIEMPO FOREIGN KEY(TIEMPO_CODIGO) REFERENCES LOS_SELECTOS.BI_TIEMPO(TIEMPO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO y LOS_SELECTOS.BI_TIEMPO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_DESCUENTO_BI_CANAL_VENTA')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_DESCUENTO_BI_CANAL_VENTA FOREIGN KEY(CANAL_CODIGO) REFERENCES LOS_SELECTOS.BI_CANAL_VENTA(CANAL_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO y LOS_SELECTOS.BI_CANAL_VENTA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_HECHO_VENTA_DESCUENTO_BI_MEDIO_DE_PAGO')
BEGIN
	ALTER TABLE LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO
	ADD CONSTRAINT FK_BI_HECHO_VENTA_DESCUENTO_BI_MEDIO_DE_PAGO FOREIGN KEY(MEDIO_DE_PAGO_CODIGO) REFERENCES LOS_SELECTOS.BI_MEDIO_DE_PAGO(MEDIO_DE_PAGO_CODIGO)
	PRINT('Foreign key entre las tablas LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO y LOS_SELECTOS.BI_MEDIO_DE_PAGO agregada')
END
GO

--------------------------------------------
---------- CREACIÓN DE PROCEDURES ----------
--------------------------------------------

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_TIEMPO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_TIEMPO(TIEMPO_ANIO, TIEMPO_MES)
	(
		SELECT YEAR(V.VENTA_FECHA) AS TIEMPO_ANIO, MONTH(V.VENTA_FECHA) AS TIEMPO_MES
		FROM LOS_SELECTOS.VENTA V
		GROUP BY YEAR(V.VENTA_FECHA), MONTH(V.VENTA_FECHA)
		UNION
 	    SELECT YEAR(C.COMPRA_FECHA) AS TIEMPO_ANIO, MONTH(C.COMPRA_FECHA) AS TIEMPO_MES
		FROM LOS_SELECTOS.COMPRA C
		GROUP BY YEAR(C.COMPRA_FECHA), MONTH(C.COMPRA_FECHA)
	)
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_TIEMPO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_TIEMPO. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_RANGO_EDAD
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_RANGO_EDAD(EDAD_CATEGORIA) VALUES('<25')
	INSERT INTO LOS_SELECTOS.BI_RANGO_EDAD(EDAD_CATEGORIA) VALUES('25 - 35')
	INSERT INTO LOS_SELECTOS.BI_RANGO_EDAD(EDAD_CATEGORIA) VALUES('35 - 55')
	INSERT INTO LOS_SELECTOS.BI_RANGO_EDAD(EDAD_CATEGORIA) VALUES('>55')
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_RANGO_EDAD)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_RANGO_EDAD. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_HECHO_VENTA_PRODUCTO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO (EDAD_CODIGO, TIEMPO_CODIGO, PROVINCIA_CODIGO, CANAL_CODIGO, MEDIO_DE_PAGO_CODIGO, CATEGORIA_CODIGO, PRODUCTO_CODIGO, MEDIO_ENVIO_CODIGO, ENVIO_PRECIO_MES_PROV_MDE, CANT_ENVIO_MES_PROV_MDE,CANT_ENVIO_MES_MDP_CV, PRODUCTO_PRECIO_TOTAL)
		SELECT
			VISTA.EDAD_CODIGO,
			VISTA.TIEMPO_CODIGO,
			VISTA.PROVINCIA_CODIGO,
			VISTA.CANAL_CODIGO,
			VISTA.MEDIO_DE_PAGO_CODIGO,
			VISTA.CATEGORIA_CODIGO,
			VISTA.PRODUCTO_CODIGO,
			VISTA.MEDIO_ENVIO_CODIGO,
			(SELECT SUM(VMEPL.VENTA_ENVIO_PRECIO)
					FROM LOS_SELECTOS.VENTA V
					INNER JOIN LOS_SELECTOS.BI_TIEMPO T ON T.TIEMPO_ANIO = year(V.VENTA_FECHA) AND T.TIEMPO_MES = month(V.VENTA_FECHA)
					INNER JOIN LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD VMEPL ON VMEPL.MEDIO_ENVIO_POR_LOCALIDAD_CODIGO = V.VENTA_MEDIO_ENVIO_POR_LOCALIDAD_CODIGO
					INNER JOIN LOS_SELECTOS.LOCALIDAD L ON L.LOCALIDAD_CODIGO = VMEPL.LOCALIDAD_CODIGO
					INNER JOIN LOS_SELECTOS.PROVINCIA P ON P.PROVINCIA_CODIGO = L.LOCALIDAD_PROVINCIA_CODIGO
					INNER JOIN LOS_SELECTOS.BI_PROVINCIA BI_P ON BI_P.PROVINCIA_NOMBRE = P.PROVINCIA_NOMBRE
					INNER JOIN LOS_SELECTOS.MEDIO_ENVIO ME ON ME.MEDIO_ENVIO_CODIGO = VMEPL.MEDIO_ENVIO_CODIGO
					INNER JOIN LOS_SELECTOS.BI_MEDIO_DE_ENVIO BI_ME ON BI_ME.MEDIO_ENVIO_NOMBRE = ME.MEDIO_ENVIO_NOMBRE
					WHERE 
					T.TIEMPO_CODIGO = VISTA.TIEMPO_CODIGO AND
					BI_P.PROVINCIA_CODIGO = VISTA.PROVINCIA_CODIGO AND
					BI_ME.MEDIO_ENVIO_CODIGO = VISTA.MEDIO_ENVIO_CODIGO
			) ENVIO_PRECIO_MES_PROV_MDE,
			(SELECT COUNT(*)
				FROM LOS_SELECTOS.VENTA V
				INNER JOIN LOS_SELECTOS.BI_TIEMPO T ON T.TIEMPO_ANIO = year(V.VENTA_FECHA) AND T.TIEMPO_MES = month(V.VENTA_FECHA)
				INNER JOIN LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD VMEPL ON VMEPL.MEDIO_ENVIO_POR_LOCALIDAD_CODIGO = V.VENTA_MEDIO_ENVIO_POR_LOCALIDAD_CODIGO
				INNER JOIN LOS_SELECTOS.LOCALIDAD L ON L.LOCALIDAD_CODIGO = VMEPL.LOCALIDAD_CODIGO
				INNER JOIN LOS_SELECTOS.PROVINCIA P ON P.PROVINCIA_CODIGO = L.LOCALIDAD_PROVINCIA_CODIGO
				INNER JOIN LOS_SELECTOS.BI_PROVINCIA BI_P ON BI_P.PROVINCIA_NOMBRE = P.PROVINCIA_NOMBRE
				INNER JOIN LOS_SELECTOS.MEDIO_ENVIO ME ON ME.MEDIO_ENVIO_CODIGO = VMEPL.MEDIO_ENVIO_CODIGO
				INNER JOIN LOS_SELECTOS.BI_MEDIO_DE_ENVIO BI_ME ON BI_ME.MEDIO_ENVIO_NOMBRE = ME.MEDIO_ENVIO_NOMBRE
	 			WHERE 
					T.TIEMPO_CODIGO = VISTA.TIEMPO_CODIGO AND
					BI_P.PROVINCIA_CODIGO = VISTA.PROVINCIA_CODIGO AND
					BI_ME.MEDIO_ENVIO_CODIGO = VISTA.MEDIO_ENVIO_CODIGO
			) CANT_ENVIO_MES_PROV_MDE,
			(SELECT COUNT(*)
				FROM LOS_SELECTOS.VENTA V
				INNER JOIN LOS_SELECTOS.BI_TIEMPO T ON T.TIEMPO_ANIO = year(V.VENTA_FECHA) AND T.TIEMPO_MES = month(V.VENTA_FECHA)
				INNER JOIN LOS_SELECTOS.MEDIO_DE_PAGO_VENTA MPV ON MPV.MEDIO_DE_PAGO_CODIGO = V.VENTA_MEDIO_DE_PAGO_CODIGO
				INNER JOIN LOS_SELECTOS.BI_MEDIO_DE_PAGO BI_MP ON BI_MP.MEDIO_DE_PAGO_NOMBRE = MPV.MEDIO_DE_PAGO_NOMBRE
				INNER JOIN LOS_SELECTOS.CANAL C ON C.CANAL_CODIGO = V.VENTA_CANAL_CODIGO
				INNER JOIN LOS_SELECTOS.BI_CANAL_VENTA BI_CV ON BI_CV.CANAL_NOMBRE = C.CANAL_NOMBRE
				WHERE 
					T.TIEMPO_CODIGO = VISTA.TIEMPO_CODIGO AND
					BI_MP.MEDIO_DE_PAGO_CODIGO = VISTA.MEDIO_DE_PAGO_CODIGO AND
					BI_CV.CANAL_CODIGO = VISTA.CANAL_CODIGO
			) CANT_ENVIO_MES_MDP_CV,
			SUM(VISTA.PRODUCTO_PRECIO_TOTAL) PRODUCTO_PRECIO_TOTAL
			FROM
			(SELECT DISTINCT 
				RE.EDAD_CODIGO,
				T.TIEMPO_CODIGO,
				P.PROVINCIA_CODIGO,
				CA.CANAL_CODIGO,
				MDPV.MEDIO_DE_PAGO_CODIGO,
				CAT.CATEGORIA_CODIGO,
				PROD.PRODUCTO_CODIGO,
				ME.MEDIO_ENVIO_CODIGO,
				VPP.PRODUCTO_PRECIO_TOTAL
				FROM LOS_SELECTOS.VENTA_POR_PRODUCTO VPP
				JOIN LOS_SELECTOS.VENTA V ON VPP.VENTA_CODIGO = V.VENTA_CODIGO
				JOIN LOS_SELECTOS.PRODUCTO_VARIANTE PV ON PV.PRODUCTO_VARIANTE_CODIGO = VPP.PRODUCTO_VARIANTE_CODIGO -- VER SI EL NOMBRE DE LA FK ESTÁ BIEN O ES VENTA_POR_PRODUCTO_PRODUCTO_VARIANTE_CODIGO Y CORREGIR EN EL DER EN ESE CASO
				JOIN LOS_SELECTOS.PRODUCTO PROD ON PROD.PRODUCTO_CODIGO = PV.PRODUCTO_CODIGO -- VER SI EL NOMBRE DE LA FK ESTÁ BIEN O ES PRODUCTO_VARIANTE_PRODUCTO_CODIGO Y CORREGIR EN EL DER EN ESE CASO
				JOIN LOS_SELECTOS.CLIENTE CLI ON V.VENTA_CLIENTE_CODIGO = CLI.CLIENTE_CODIGO
				JOIN LOS_SELECTOS.MEDIO_ENVIO_POR_LOCALIDAD MDEPL ON MDEPL.MEDIO_ENVIO_POR_LOCALIDAD_CODIGO = V.VENTA_MEDIO_ENVIO_POR_LOCALIDAD_CODIGO
				JOIN LOS_SELECTOS.LOCALIDAD L ON L.LOCALIDAD_CODIGO = MDEPL.LOCALIDAD_CODIGO -- VER SI EL NOMBRE DE LA FK ESTÁ BIEN
				JOIN LOS_SELECTOS.PROVINCIA P ON L.LOCALIDAD_PROVINCIA_CODIGO = P.PROVINCIA_CODIGO
				JOIN LOS_SELECTOS.CANAL CA ON V.VENTA_CANAL_CODIGO = CA.CANAL_CODIGO
				JOIN LOS_SELECTOS.MEDIO_DE_PAGO_VENTA MDPV ON MDPV.MEDIO_DE_PAGO_CODIGO = V.VENTA_MEDIO_DE_PAGO_CODIGO
				JOIN LOS_SELECTOS.CATEGORIA CAT ON CAT.CATEGORIA_CODIGO = PROD.PRODUCTO_CATEGORIA_CODIGO
				JOIN LOS_SELECTOS.MEDIO_ENVIO ME ON ME.MEDIO_ENVIO_CODIGO = MDEPL.MEDIO_ENVIO_CODIGO
				JOIN LOS_SELECTOS.BI_RANGO_EDAD RE ON RE.EDAD_CATEGORIA = LOS_SELECTOS.BI_FUNCION_RANGO_ETARIO(CLI.CLIENTE_FECHA_NAC) -- VER EL NOMBRE QUE SE VA A USAR Y VER QUE RETORNE UN NVARCHAR
				JOIN LOS_SELECTOS.BI_TIEMPO T ON T.TIEMPO_ANIO = year(V.VENTA_FECHA) AND T.TIEMPO_MES = month(V.VENTA_FECHA)
			) VISTA
			GROUP BY 
			VISTA.EDAD_CODIGO,
			VISTA.TIEMPO_CODIGO,
			VISTA.PROVINCIA_CODIGO,
			VISTA.CANAL_CODIGO,
			VISTA.MEDIO_DE_PAGO_CODIGO,
			VISTA.CATEGORIA_CODIGO,
			VISTA.PRODUCTO_CODIGO,
			VISTA.MEDIO_ENVIO_CODIGO
			ORDER BY VISTA.TIEMPO_CODIGO, VISTA.PROVINCIA_CODIGO, VISTA.MEDIO_ENVIO_CODIGO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_PROVINCIA
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_PROVINCIA (PROVINCIA_CODIGO, PROVINCIA_NOMBRE)
		SELECT DISTINCT PROVINCIA_CODIGO, PROVINCIA_NOMBRE FROM LOS_SELECTOS.PROVINCIA
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_PROVINCIA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_PROVINCIA. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_MEDIO_DE_PAGO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_MEDIO_DE_PAGO (MEDIO_DE_PAGO_CODIGO, MEDIO_DE_PAGO_NOMBRE, MEDIO_DE_PAGO_COSTO)
		SELECT DISTINCT MEDIO_DE_PAGO_CODIGO, MEDIO_DE_PAGO_NOMBRE, MEDIO_DE_PAGO_COSTO FROM LOS_SELECTOS.MEDIO_DE_PAGO_VENTA
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_MEDIO_DE_PAGO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_MEDIO_DE_PAGO. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_CATEGORIA
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_CATEGORIA (CATEGORIA_CODIGO, CATEGORIA_NOMBRE)
		SELECT C.CATEGORIA_CODIGO, C.CATEGORIA_NOMBRE
		FROM LOS_SELECTOS.CATEGORIA C
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_CATEGORIA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_CATEGORIA. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_PRODUCTO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_PRODUCTO (PRODUCTO_CODIGO, PRODUCTO_NOMBRE)
		SELECT P.PRODUCTO_CODIGO, P.PRODUCTO_NOMBRE
		FROM LOS_SELECTOS.PRODUCTO P
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_PRODUCTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_PRODUCTO. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_CANAL_VENTA
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_CANAL_VENTA (CANAL_CODIGO, CANAL_COSTO, CANAL_NOMBRE)
		SELECT C.CANAL_CODIGO, C.CANAL_COSTO, C.CANAL_NOMBRE
		FROM LOS_SELECTOS.CANAL C
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_CANAL_VENTA)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_CANAL_VENTA. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_HECHO_COMPRA_PRODUCTO
AS
	BEGIN
	INSERT INTO LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO (PROVEEDOR_CUIT, TIEMPO_CODIGO, PRODUCTO_CODIGO, PRODUCTO_CANTIDAD,PRODUCTO_PRECIO_UNITARIO)
		SELECT VISTA.PROVEEDOR_CUIT, VISTA.TIEMPO_CODIGO, VISTA.PRODUCTO_CODIGO, 
		SUM(VISTA.PRODUCTO_CANTIDAD) PRODUCTO_CANTIDAD,
		AVG(VISTA.PRODUCTO_PRECIO_UNITARIO) PRODUCTO_PRECIO_UNITARIO
		FROM(SELECT DISTINCT
			CPP.COMPRA_POR_PRODUCTO_CODIGO,
			PRO.PROVEEDOR_CUIT,
			T.TIEMPO_CODIGO,
			P.PRODUCTO_CODIGO,
			CPP.PRODUCTO_CANTIDAD,
			CPP.PRODUCTO_PRECIO_TOTAL/CPP.PRODUCTO_CANTIDAD PRODUCTO_PRECIO_UNITARIO
			FROM LOS_SELECTOS.COMPRA_POR_PRODUCTO CPP
			JOIN LOS_SELECTOS.COMPRA C ON CPP.COMPRA_NUMERO = C.COMPRA_NUMERO
			JOIN LOS_SELECTOS.PRODUCTO_VARIANTE PV ON PV.PRODUCTO_VARIANTE_CODIGO = CPP.PRODUCTO_VARIANTE_CODIGO 
			JOIN LOS_SELECTOS.PRODUCTO P ON P.PRODUCTO_CODIGO = PV.PRODUCTO_CODIGO 
			JOIN LOS_SELECTOS.PROVEEDOR PRO ON C.PROVEEDOR_CUIT = PRO.PROVEEDOR_CUIT
			JOIN LOS_SELECTOS.BI_TIEMPO T ON T.TIEMPO_ANIO = year(C.COMPRA_FECHA) AND T.TIEMPO_MES = month(C.COMPRA_FECHA)
			) VISTA
		GROUP BY PROVEEDOR_CUIT, TIEMPO_CODIGO, PRODUCTO_CODIGO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_MEDIO_DE_ENVIO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_MEDIO_DE_ENVIO (MEDIO_ENVIO_CODIGO, MEDIO_ENVIO_NOMBRE)
		SELECT DISTINCT MEDIO_ENVIO_CODIGO, MEDIO_ENVIO_NOMBRE FROM LOS_SELECTOS.MEDIO_ENVIO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_MEDIO_DE_ENVIO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_MEDIO_DE_ENVIO. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_TIPO_DE_DESCUENTO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_TIPO_DE_DESCUENTO (TIPO_DESCUENTO_CODIGO, TIPO_DESCUENTO_NOMBRE)
		SELECT DISTINCT DESCUENTO_CONCEPTO_CODIGO, DESCUENTO_CONCEPTO_NOMBRE FROM LOS_SELECTOS.DESCUENTO_CONCEPTO
		UNION SELECT 4, 'Cupon'
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_TIPO_DE_DESCUENTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_TIPO_DE_DESCUENTO. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

CREATE PROCEDURE LOS_SELECTOS.MIGRAR_TABLA_BI_HECHO_VENTA_DESCUENTO
AS
BEGIN
	INSERT INTO LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO (TIPO_DESCUENTO_CODIGO,  TIEMPO_CODIGO, CANAL_CODIGO, MEDIO_DE_PAGO_CODIGO, DESCUENTO_IMPORTE)
		SELECT
			VISTA.TIPO_DESCUENTO_CODIGO,
			VISTA.TIEMPO_CODIGO,
			VISTA.CANAL_CODIGO,
			VISTA.MEDIO_DE_PAGO_CODIGO,
			SUM(VISTA.DESCUENTO_IMPORTE) DESCUENTO_IMPORTE 
		FROM (SELECT
				BTD.TIPO_DESCUENTO_CODIGO,
				BT.TIEMPO_CODIGO,
				BCV.CANAL_CODIGO,
				MDP.MEDIO_DE_PAGO_CODIGO,
				DPV.DESCUENTO_IMPORTE
			FROM LOS_SELECTOS.VENTA V
			INNER JOIN LOS_SELECTOS.DESCUENTO_POR_VENTA DPV on DPV.VENTA_CODIGO = V.VENTA_CODIGO
			INNER JOIN LOS_SELECTOS.DESCUENTO_CONCEPTO DC on DC.DESCUENTO_CONCEPTO_CODIGO = DPV.DESCUENTO_CONCEPTO_CODIGO
			INNER JOIN LOS_SELECTOS.CANAL C on C.CANAL_CODIGO = V.VENTA_CANAL_CODIGO
			INNER JOIN LOS_SELECTOS.BI_TIPO_DE_DESCUENTO BTD on BTD.TIPO_DESCUENTO_CODIGO = DC.DESCUENTO_CONCEPTO_CODIGO
			INNER JOIN LOS_SELECTOS.BI_TIEMPO BT ON BT.TIEMPO_ANIO = year(V.VENTA_FECHA) AND BT.TIEMPO_MES = month(V.VENTA_FECHA)
			INNER JOIN LOS_SELECTOS.BI_CANAL_VENTA BCV on BCV.CANAL_CODIGO = C.CANAL_CODIGO
			INNER JOIN LOS_SELECTOS.BI_MEDIO_DE_PAGO MDP ON MDP.MEDIO_DE_PAGO_CODIGO =V.VENTA_MEDIO_DE_PAGO_CODIGO
			UNION (SELECT
						4,
						BT.TIEMPO_CODIGO,
						BCV.CANAL_CODIGO,
						MP.MEDIO_DE_PAGO_CODIGO,
						VPC.CUPON_IMPORTE DESCUENTO_IMPORTE
					FROM LOS_SELECTOS.VENTA V
					INNER JOIN LOS_SELECTOS.VENTA_POR_CUPON VPC on VPC.VENTA_CODIGO = V.VENTA_CODIGO
					INNER JOIN LOS_SELECTOS.CANAL C on C.CANAL_CODIGO = V.VENTA_CANAL_CODIGO
					INNER JOIN LOS_SELECTOS.BI_TIEMPO BT ON BT.TIEMPO_ANIO = year(V.VENTA_FECHA) AND BT.TIEMPO_MES = month(V.VENTA_FECHA)
					INNER JOIN LOS_SELECTOS.BI_CANAL_VENTA BCV on BCV.CANAL_CODIGO = C.CANAL_CODIGO
					INNER JOIN LOS_SELECTOS.BI_MEDIO_DE_PAGO MP on MP.MEDIO_DE_PAGO_CODIGO = MP.MEDIO_DE_PAGO_CODIGO )) AS VISTA
					GROUP BY  VISTA.TIPO_DESCUENTO_CODIGO, VISTA.TIEMPO_CODIGO,VISTA.CANAL_CODIGO, VISTA.MEDIO_DE_PAGO_CODIGO
					ORDER BY VISTA.TIPO_DESCUENTO_CODIGO, VISTA.TIEMPO_CODIGO,VISTA.CANAL_CODIGO,MEDIO_DE_PAGO_CODIGO
	DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
	SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO)
	PRINT('Datos migrados a la tabla LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO. Cantidad de registros: ' + @CANTIDAD_REGISTROS)
END
GO

---------------------------------------------
---------- EJECUCIÓN DE PROCEDURES ----------
---------------------------------------------

EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_CATEGORIA
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_PRODUCTO
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_CANAL_VENTA
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_MEDIO_DE_PAGO
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_MEDIO_DE_ENVIO
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_TIPO_DE_DESCUENTO
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_TIEMPO
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_PROVINCIA
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_RANGO_EDAD
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_HECHO_COMPRA_PRODUCTO
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_HECHO_VENTA_PRODUCTO
EXEC LOS_SELECTOS.MIGRAR_TABLA_BI_HECHO_VENTA_DESCUENTO
GO

---------------------------------------------
---------- CREACIÓN DE VISTAS ----------
---------------------------------------------

--VISTA 1

IF OBJECT_ID('LOS_SELECTOS.GANANCIA_POR_CANAL_DE_VENTA_POR_MES') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.GANANCIA_POR_CANAL_DE_VENTA_POR_MES
    PRINT('Vista LOS_SELECTOS.GANANCIA_POR_CANAL_DE_VENTA_POR_MES eliminado')
END
GO

CREATE VIEW LOS_SELECTOS.GANANCIA_POR_CANAL_DE_VENTA_POR_MES
AS
	SELECT
		T.TIEMPO_ANIO,
		T.TIEMPO_MES,
		CV.CANAL_NOMBRE,
		SUM(HVP.PRODUCTO_PRECIO_TOTAL) AS TOTAL_VENTAS,
		SUM(HCP.PRODUCTO_CANTIDAD*HCP.PRODUCTO_PRECIO_UNITARIO) AS TOTAL_COMPRAS,
		(SELECT SUM(VENTA_PERIODICIDAD.MEDIO_DE_PAGO_COSTO)
				FROM (SELECT MDP.MEDIO_DE_PAGO_COSTO
						FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO VP
						INNER JOIN LOS_SELECTOS.BI_MEDIO_DE_PAGO MDP ON VP.MEDIO_DE_PAGO_CODIGO = MDP.MEDIO_DE_PAGO_CODIGO
						INNER JOIN LOS_SELECTOS.BI_TIEMPO T1 ON VP.TIEMPO_CODIGO = T1.TIEMPO_CODIGO
						INNER JOIN LOS_SELECTOS.BI_CANAL_VENTA CV1 ON VP.CANAL_CODIGO = CV1.CANAL_CODIGO
						WHERE T1.TIEMPO_ANIO = T.TIEMPO_ANIO AND T1.TIEMPO_MES = T.TIEMPO_MES
						AND CV1.CANAL_NOMBRE = CV.CANAL_NOMBRE
					  ) VENTA_PERIODICIDAD
		) COSTOS_DE_MEDIO_DE_PAGO,
		SUM(HVP.PRODUCTO_PRECIO_TOTAL)
		- SUM(HCP.PRODUCTO_CANTIDAD*HCP.PRODUCTO_PRECIO_UNITARIO)
		- (SELECT SUM(VENTA_PERIODICIDAD.MEDIO_DE_PAGO_COSTO)
						FROM (SELECT MDP.MEDIO_DE_PAGO_COSTO
								FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO VP
								INNER JOIN LOS_SELECTOS.BI_MEDIO_DE_PAGO MDP ON VP.MEDIO_DE_PAGO_CODIGO = MDP.MEDIO_DE_PAGO_CODIGO
								INNER JOIN LOS_SELECTOS.BI_TIEMPO T1 ON VP.TIEMPO_CODIGO = T1.TIEMPO_CODIGO
								INNER JOIN LOS_SELECTOS.BI_CANAL_VENTA CV1 ON VP.CANAL_CODIGO = CV1.CANAL_CODIGO
								WHERE T1.TIEMPO_ANIO = T.TIEMPO_ANIO AND T1.TIEMPO_MES = T.TIEMPO_MES
								AND CV1.CANAL_NOMBRE = CV.CANAL_NOMBRE
							  ) VENTA_PERIODICIDAD
		  ) AS GANANCIA
		FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO HVP
		JOIN LOS_SELECTOS.BI_PRODUCTO P ON P.PRODUCTO_CODIGO = HVP.PRODUCTO_CODIGO
		JOIN LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO HCP ON HCP.PRODUCTO_CODIGO = P.PRODUCTO_CODIGO
		JOIN LOS_SELECTOS.BI_TIEMPO T ON T.TIEMPO_CODIGO = HVP.TIEMPO_CODIGO OR HCP.TIEMPO_CODIGO = T.TIEMPO_CODIGO
		JOIN LOS_SELECTOS.BI_CANAL_VENTA CV ON CV.CANAL_CODIGO = HVP.CANAL_CODIGO
		JOIN LOS_SELECTOS.BI_MEDIO_DE_PAGO MP ON MP.MEDIO_DE_PAGO_CODIGO = HVP.MEDIO_DE_PAGO_CODIGO
		GROUP BY T.TIEMPO_ANIO, T.TIEMPO_MES, CV.CANAL_NOMBRE
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.GANANCIA_POR_CANAL_DE_VENTA_POR_MES)
PRINT('Vista LOS_SELECTOS.GANANCIA_POR_CANAL_DE_VENTA_POR_MES creada. Cantidad de registros: ' + @CANTIDAD_REGISTROS)

--VISTA 2

IF OBJECT_ID('LOS_SELECTOS.TOP_5_PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.TOP_5_PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL
    PRINT('Vista LOS_SELECTOS.TOP_5_PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL eliminada')
END
GO

CREATE VIEW LOS_SELECTOS.TOP_5_PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL
AS
	SELECT TIEMPO_ANIO, PRODUCTO_NOMBRE, PORCENTAJE_RENTABILIDAD FROM (
		SELECT T.TIEMPO_ANIO, P.PRODUCTO_NOMBRE, (SUM(HVP.PRODUCTO_PRECIO_TOTAL) - SUM(HCP.PRODUCTO_CANTIDAD * HCP.PRODUCTO_PRECIO_UNITARIO))/SUM(HVP.PRODUCTO_PRECIO_TOTAL) * 100 AS PORCENTAJE_RENTABILIDAD, ROW_NUMBER() OVER (PARTITION BY T.TIEMPO_ANIO ORDER BY (SUM(HVP.PRODUCTO_PRECIO_TOTAL) - SUM(HCP.PRODUCTO_CANTIDAD * HCP.PRODUCTO_PRECIO_UNITARIO))/SUM(HVP.PRODUCTO_PRECIO_TOTAL) * 100 DESC) AS TOP_MAYOR_RENTABILIDAD
		FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO HVP
		JOIN LOS_SELECTOS.BI_PRODUCTO P ON P.PRODUCTO_CODIGO = HVP.PRODUCTO_CODIGO
		JOIN LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO HCP ON HCP.PRODUCTO_CODIGO = P.PRODUCTO_CODIGO
		JOIN LOS_SELECTOS.BI_TIEMPO T ON T.TIEMPO_CODIGO = HVP.TIEMPO_CODIGO
		GROUP BY T.TIEMPO_ANIO, P.PRODUCTO_NOMBRE
		) RENTABILIDADES
	WHERE TOP_MAYOR_RENTABILIDAD <= 5
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.TOP_5_PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL)
PRINT('Vista LOS_SELECTOS.TOP_5_PRODUCTOS_CON_MAYOR_RENTABILIDAD_ANUAL creada. Cantidad de registros: ' + @CANTIDAD_REGISTROS)

--VISTA 3

IF OBJECT_ID('LOS_SELECTOS.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES
    PRINT('Vista LOS_SELECTOS.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES eliminado')
END
GO

CREATE VIEW LOS_SELECTOS.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES
AS
	SELECT E.EDAD_CATEGORIA,T.TIEMPO_ANIO,T.TIEMPO_MES,vp.CATEGORIA_CODIGO,COUNT(vp.CATEGORIA_CODIGO)  as [VECES_VENDIDA_CATEGORIA]
		FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO VP 
		JOIN LOS_SELECTOS.BI_CATEGORIA C ON C.CATEGORIA_CODIGO = VP.CATEGORIA_CODIGO
		JOIN LOS_SELECTOS.BI_TIEMPO T ON VP.TIEMPO_CODIGO = T.TIEMPO_CODIGO 
		JOIN LOS_SELECTOS.BI_RANGO_EDAD E ON VP.EDAD_CODIGO = E.EDAD_CODIGO
		WHERE vp.CATEGORIA_CODIGO in(SELECT TOP 5 vp.CATEGORIA_CODIGO FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO vp	GROUP BY vp.CATEGORIA_CODIGO ORDER BY COUNT(DISTINCT vp.CATEGORIA_CODIGO) DESC)
		GROUP BY  E.EDAD_CATEGORIA,T.TIEMPO_ANIO,T.TIEMPO_MES,vp.CATEGORIA_CODIGO
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES)
PRINT('Vista LOS_SELECTOS.TOP_5_CATEGORIAS_VENDIDAS_X_RANGO_ETARIO_CLIENTES_X_MES creada. Cantidad de registros: ' + @CANTIDAD_REGISTROS)

--VISTA 4

IF OBJECT_ID('LOS_SELECTOS.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES
    PRINT('Vista LOS_SELECTOS.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES eliminado')
END
GO

CREATE VIEW LOS_SELECTOS.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES
AS
	SELECT 
		SUM(VP.PRODUCTO_PRECIO_TOTAL) - SUM(VP.CANT_ENVIO_MES_MDP_CV) * MDP.MEDIO_DE_PAGO_COSTO - (
			SELECT SUM(DESCUENTO_IMPORTE)
			FROM LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO BHVI
			WHERE BHVI.TIEMPO_CODIGO = T.TIEMPO_CODIGO AND
			BHVI.MEDIO_DE_PAGO_CODIGO = HVD.MEDIO_DE_PAGO_CODIGO
			GROUP BY TIEMPO_CODIGO,MEDIO_DE_PAGO_CODIGO
		 ) AS [INGRESOS_TOTALES_MENOS_COSTO_MENOS_DESCUENTOS],
		 T.TIEMPO_CODIGO,
		 HVD.MEDIO_DE_PAGO_CODIGO
		 FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO VP 
		 JOIN LOS_SELECTOS.BI_MEDIO_DE_PAGO MDP ON MDP.MEDIO_DE_PAGO_CODIGO = VP.MEDIO_DE_PAGO_CODIGO
		 JOIN LOS_SELECTOS.BI_TIEMPO T ON VP.TIEMPO_CODIGO = T.TIEMPO_CODIGO
		 JOIN LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO HVD ON HVD.TIEMPO_CODIGO = T.TIEMPO_CODIGO AND HVD.MEDIO_DE_PAGO_CODIGO = MDP.MEDIO_DE_PAGO_CODIGO
		 GROUP BY T.TIEMPO_CODIGO, HVD.MEDIO_DE_PAGO_CODIGO, MDP.MEDIO_DE_PAGO_COSTO
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES)
PRINT('Vista LOS_SELECTOS.LOS_SELECTOS.INGRESOS_TOTALES_X_MEDIODEPAGO_X_MES creada. Cantidad de registros: ' + @CANTIDAD_REGISTROS)

/*
SELECT TIEMPO_CODIGO,MEDIO_DE_PAGO_CODIGO,SUM(DESCUENTO_IMPORTE) FROM LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO
GROUP BY TIEMPO_CODIGO,MEDIO_DE_PAGO_CODIGO
*/

--VISTA 5

IF OBJECT_ID('LOS_SELECTOS.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES
    PRINT('Vista LOS_SELECTOS.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES eliminado')
END
GO

CREATE VIEW LOS_SELECTOS.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES
AS
	SELECT T.TIEMPO_ANIO,T.TIEMPO_MES,C.CANAL_NOMBRE,TD.TIPO_DESCUENTO_NOMBRE,SUM(VD.DESCUENTO_IMPORTE) AS [Importe Total]
		FROM LOS_SELECTOS.BI_HECHO_VENTA_DESCUENTO VD 
		JOIN LOS_SELECTOS.BI_CANAL_VENTA C ON C.CANAL_CODIGO = VD.CANAL_CODIGO
		JOIN LOS_SELECTOS.BI_TIEMPO T ON VD.TIEMPO_CODIGO = T.TIEMPO_CODIGO 
		JOIN LOS_SELECTOS.BI_TIPO_DE_DESCUENTO TD ON VD.TIPO_DESCUENTO_CODIGO = TD.TIPO_DESCUENTO_CODIGO
		GROUP BY  T.TIEMPO_ANIO,T.TIEMPO_MES,C.CANAL_NOMBRE,TD.TIPO_DESCUENTO_NOMBRE
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES)
PRINT('Vista LOS_SELECTOS.IMPORTE_TOTAL_DESCUENTOS_SEGUN_TIPO_DE_DESCUENTO_X_CANAL_VENTA_X_MES creada. Cant filas: ' + @CANTIDAD_REGISTROS)

--VISTA 6

IF OBJECT_ID('LOS_SELECTOS.PORCENTAJE_DE_ENVIOS_PROVINCIA_X_MES') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.PORCENTAJE_DE_ENVIOS_PROVINCIA_X_MES
    PRINT('Vista LOS_SELECTOS.PORCENTAJE_DE_ENVIOS_PROVINCIA_X_MES eliminado')
END
GO

CREATE VIEW LOS_SELECTOS.PORCENTAJE_DE_ENVIOS_PROVINCIA_X_MES
AS
	SELECT
		T.TIEMPO_ANIO,
		T.TIEMPO_MES,
		P.PROVINCIA_NOMBRE,
		(round(COUNT(P.PROVINCIA_NOMBRE) * 100.00/ 
			(SELECT COUNT(*)
				FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO VP2 
				JOIN LOS_SELECTOS.BI_TIEMPO T2 ON VP2.TIEMPO_CODIGO = T2.TIEMPO_CODIGO 
				WHERE T2.TIEMPO_ANIO = T.TIEMPO_ANIO AND T2.TIEMPO_MES = T.TIEMPO_MES)
			, 2)
		) AS [PORCENTAJE]
			FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO VP 
			JOIN LOS_SELECTOS.BI_TIEMPO T ON VP.TIEMPO_CODIGO = T.TIEMPO_CODIGO 
			JOIN LOS_SELECTOS.BI_PROVINCIA P ON P.PROVINCIA_CODIGO = VP.PROVINCIA_CODIGO
			GROUP BY T.TIEMPO_ANIO,T.TIEMPO_MES,P.PROVINCIA_NOMBRE 
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.PORCENTAJE_DE_ENVIOS_PROVINCIA_X_MES)
PRINT('Vista LOS_SELECTOS.PORCENTAJE_DE_ENVIOS_PROVINCIA_X_MES creada. Cantidad de registros: ' + @CANTIDAD_REGISTROS)

--VISTA 7

IF OBJECT_ID('LOS_SELECTOS.PROMEDIO_DE_ENVIO_PROVINCIA_X_MEDIO_DE_ENVIO_ANUAL') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.PROMEDIO_DE_ENVIO_PROVINCIA_X_MEDIO_DE_ENVIO_ANUAL
    PRINT('Vista LOS_SELECTOS.PROMEDIO_DE_ENVIO_PROVINCIA_X_MEDIO_DE_ENVIO_ANUAL eliminado')
END
GO

CREATE VIEW LOS_SELECTOS.PROMEDIO_DE_ENVIO_PROVINCIA_X_MEDIO_DE_ENVIO_ANUAL
AS
	SELECT 
		T.TIEMPO_ANIO,
		P.PROVINCIA_NOMBRE,
		MDE.MEDIO_ENVIO_NOMBRE,
		(SELECT AVG(ENVIOS.ENVIO_PRECIO_MES_PROV_MDE)
				FROM (SELECT DISTINCT HVP.TIEMPO_CODIGO, HVP.PROVINCIA_CODIGO, HVP.MEDIO_ENVIO_CODIGO, ENVIO_PRECIO_MES_PROV_MDE
						FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO HVP
						INNER JOIN LOS_SELECTOS.BI_TIEMPO BI_T ON BI_T.TIEMPO_CODIGO = HVP.TIEMPO_CODIGO
						INNER JOIN LOS_SELECTOS.BI_PROVINCIA BI_P ON BI_P.PROVINCIA_CODIGO = HVP.PROVINCIA_CODIGO
						INNER JOIN LOS_SELECTOS.BI_MEDIO_DE_ENVIO BI_MDE ON BI_MDE.MEDIO_ENVIO_CODIGO = HVP.MEDIO_ENVIO_CODIGO
						WHERE BI_T.TIEMPO_ANIO= T.TIEMPO_ANIO AND BI_P.PROVINCIA_NOMBRE = P.PROVINCIA_NOMBRE AND BI_MDE.MEDIO_ENVIO_NOMBRE= MDE.MEDIO_ENVIO_NOMBRE
					 ) ENVIOS
		) PROMEDIO_ENVIO_PRECIO
		FROM LOS_SELECTOS.BI_HECHO_VENTA_PRODUCTO VP 
		JOIN LOS_SELECTOS.BI_TIEMPO T ON VP.TIEMPO_CODIGO = T.TIEMPO_CODIGO 
		JOIN LOS_SELECTOS.BI_PROVINCIA P ON P.PROVINCIA_CODIGO = VP.PROVINCIA_CODIGO
		JOIN LOS_SELECTOS.BI_MEDIO_DE_ENVIO MDE ON MDE.MEDIO_ENVIO_CODIGO=VP.MEDIO_ENVIO_CODIGO
		GROUP BY T.TIEMPO_ANIO, P.PROVINCIA_NOMBRE, MDE.MEDIO_ENVIO_NOMBRE
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.PROMEDIO_DE_ENVIO_PROVINCIA_X_MEDIO_DE_ENVIO_ANUAL)
PRINT('Vista LOS_SELECTOS.PROMEDIO_DE_ENVIO_PROVINCIA_X_MEDIO_DE_ENVIO_ANUAL creada. Cantidad de registros: ' + @CANTIDAD_REGISTROS)

--VISTA 8

IF OBJECT_ID('LOS_SELECTOS.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL
    PRINT('Vista LOS_SELECTOS.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL eliminado')
END
GO

CREATE VIEW LOS_SELECTOS.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL
AS
	SELECT
		CP.PROVEEDOR_CUIT,
		T.TIEMPO_ANIO,
		(MAX(CP.PRODUCTO_PRECIO_UNITARIO) - MIN(CP.PRODUCTO_PRECIO_UNITARIO)) / MIN(CP.PRODUCTO_PRECIO_UNITARIO) PRECIO_PROMEDIO
			FROM LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO CP
			INNER JOIN LOS_SELECTOS.BI_TIEMPO T ON CP.TIEMPO_CODIGO = T.TIEMPO_CODIGO
			GROUP BY T.TIEMPO_ANIO, CP.PROVEEDOR_CUIT
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL)
PRINT('Vista LOS_SELECTOS.AUMENTO_DE_PRECIOS_X_PROVEEDOR_ANUAL creada. Cantidad de registros: ' + @CANTIDAD_REGISTROS)

--VISTA 9

IF OBJECT_ID('LOS_SELECTOS.TOP_3_PRODUCTOS_CON_MAYOR_REPOSICION_ANUAL') IS NOT NULL
BEGIN
	DROP VIEW LOS_SELECTOS.TOP_3_PRODUCTOS_CON_MAYOR_REPOSICION_ANUAL
    PRINT('Vista LOS_SELECTOS.TOP_3_PRODUCTOS_CON_MAYOR_REPOSICION_ANUAL eliminado')
END
GO

CREATE VIEW LOS_SELECTOS.TOP_3_PRODUCTOS_CON_MAYOR_REPOSICION_ANUAL
AS
	SELECT
		TIEMPO_ANIO,
		TIEMPO_MES,
		PRODUCTO_NOMBRE,
		CANTIDAD_REPOSICION
			FROM (SELECT T.TIEMPO_ANIO, T.TIEMPO_MES, P.PRODUCTO_NOMBRE, SUM(HCP.PRODUCTO_CANTIDAD) AS CANTIDAD_REPOSICION, ROW_NUMBER() OVER (PARTITION BY T.TIEMPO_ANIO, T.TIEMPO_MES ORDER BY SUM(HCP.PRODUCTO_CANTIDAD) DESC) AS TOP_MAYOR_REPOSICION FROM LOS_SELECTOS.BI_HECHO_COMPRA_PRODUCTO HCP
					JOIN LOS_SELECTOS.BI_PRODUCTO P ON P.PRODUCTO_CODIGO = HCP.PRODUCTO_CODIGO
					JOIN LOS_SELECTOS.BI_TIEMPO T ON T.TIEMPO_CODIGO = HCP.TIEMPO_CODIGO
					GROUP BY T.TIEMPO_ANIO, T.TIEMPO_MES, P.PRODUCTO_NOMBRE
				 ) REPOSICIONES
		WHERE TOP_MAYOR_REPOSICION <=3
GO

DECLARE @CANTIDAD_REGISTROS NVARCHAR(255)
SET @CANTIDAD_REGISTROS = (SELECT COUNT(*) FROM LOS_SELECTOS.TOP_3_PRODUCTOS_CON_MAYOR_REPOSICION_ANUAL)
PRINT('Vista LOS_SELECTOS.TOP_3_PRODUCTOS_CON_MAYOR_REPOSICION_ANUAL creada. Cantidad de registros: ' + @CANTIDAD_REGISTROS)

